### ISSUE TITLE
Enhance readability of topbar

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#100]
When using a bright background the text in the topbar is difficult to read:
![bildschirmfoto von 2018-04-07 14-23-41](https://user-images.githubusercontent.com/36449926/38454861-876e2d12-3a6f-11e8-9f06-323e9c84dd56.png)
(this wallpaper is one of the shipped wallpapers of 17.10 - should we care about this if 18.04 gets no bright wallpaper?)

**possible solution:**
when hover / mouse-over the text gets a shadow which increases readability a lot. How about letting the **shadow always be activated**?:
![bildschirmfoto von 2018-04-07 14-23-49](https://user-images.githubusercontent.com/36449926/38454888-cde7b5ce-3a6f-11e8-84d2-21cb63b7d1bc.png)
On hover / mouse-over the text in the topbar could get a **gray underline** or a **stronger** shadow.

**Comment by clobrano** [comment]
Thank you @NusiNusi to point that out
