### ISSUE TITLE
Add more animations to the gnome-shell-theme

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#105]
To avoid confusion we should talk here about possible animations for the gnome-shell-theme.
Are these animations possible for the gnome-shell-topbar?
This animation (yes, in orange) should be used when **clicked** on "Activities":
![peek 2018-04-11 20-28](https://user-images.githubusercontent.com/36449926/38635848-f01d8c90-3dc6-11e8-9839-d980c900fa03.gif)
For the right side the line should come from the right edge of the screen (so the same animation but mirrored).
For the middle (calendar) the line should come from the middle and evolve to the left and the right (similar to the suggested animations for stackswicher)
![peek 2018-04-11 21-16](https://user-images.githubusercontent.com/36449926/38638157-a6c6cc9e-3dcd-11e8-9536-6d54d384b6b3.gif)

Source of the animation can be found here: http://littlesnippets.net/some-inspiration-for-menus-using-animated-lines/
**Is the css-code somehow useful? You can find it there too.**

**Comment by Feichtmeier** [comment]
Nice idea!
Hmmmm I hate that I don't got animations in my VM -.- need to fix that. 
@clobrano is this possible with
animation:         increase 3s; 
animation-fill-mode: forwards; 
?
You would need to do it, I got no animations in my VM *cry*
Found some possible solutions on
https://stackoverflow.com/questions/39993244/line-drawing-animation-with-pure-css

**Comment by clobrano** [comment]
I haven't tried much with animations yet, but in any case I won't be able to test it before about a week

**Comment by Feichtmeier** [comment]
I realzied that we could have a potential blocker for animated underlines:

the popping up of the popup (...) itself is animated too. Maybe this could be a bit too much?

**Comment by NusiNusi** [comment]
@Feichtmeier  tell me what exactly to do and i could test it for us and make some gifs.

**Comment by Feichtmeier** [comment]
No idea really, I am just undecided if this  animation is not "too much" when the showing up of the popup window is animated itself :D That's why our designers could look into this question if they got some spare time. Also, gnome shell allready got some performance problems at the moment. 
So, no idea what you could do :D I guess posting some suggestions is always nice and inspiring for the designers!

**Comment by NusiNusi** [comment]
IMHO it is not too much at all. We should at least test it.
"Probieren geht über Studieren" (Testing is sometimes better than studying) ;)

**Comment by Luxamman** [comment]
I guess some movement (animations) is okay, but too many and constantly could get on our nerves. 

We should keep it in mind to test them at least in some situations (like the breadcrumbs in Files for example) and see how they look if they work as expected.

**Comment by Feichtmeier** [comment]
Sad news, I've tried a lot but it seems impossible to change the gnome shell animations. We would need to change the shell code which is prbly nothing we want =) So it's a wontfix or a cantfix
