### ISSUE TITLE
Need to disconnect and re-log me to get the communitheme works

### ISSUE THREAD

**Issue by Huluti** [ubuntu/gnome-shell-communitheme#107]
Hi!
I have a very strange issue with the theme.
I have upgraded to Ubuntu 18.04 from Ubuntu 17.10 and I've installed the snap theme while I was using the ppa before.
Each time I restart my computer and I log me, the session use the Adwaita theme and if I close my session and I re-log me, the session use the correct communitheme...

I don't know what infos I can give you so don't hesitate to ask me more infos.
Thank's in advance!

**Comment by Huluti** [comment]
Yes I don't have it anymore.

**Comment by Feichtmeier** [comment]
Hm this sounds pretty strange. 
Maybe @didrocks has some ideas on that
@Huluti could you try to 
sudo snap remove communitheme
reboot
sudo snap install communitheme
select the communitheme session in the login screen (!!!)
see if the error persists?

**Comment by Huluti** [comment]
Same thing...
Here's a screenshot of the first session I have:

![capture du 2018-04-16 17-08-53-min](https://user-images.githubusercontent.com/5782198/38817826-7e833680-4199-11e8-991f-0ec3f075d89d.png)

Here's a screenshot after the second login:

![capture du 2018-04-16 17-10-29-min](https://user-images.githubusercontent.com/5782198/38817834-8184501c-4199-11e8-8d8b-6b2940eeb09d.png)

**Comment by wandrewkeech** [comment]
Did you try using `$ communitheme.reset` to jiggle the theme?

**Comment by Huluti** [comment]
Same problem on a fresh 18.04 install...

**Comment by didrocks** [comment]
When you first log and end up with adwaita, please run "env" and paste the output here.

Also, have you changed anything in your snapd settings?
Try logging in a tty (so, not graphically), then wait for 30s and log in graphically.

I think your snaps aren't mounted quickly enough by snapd, and so, it would be something to report on forum.snapcraft.io

**Comment by Huluti** [comment]
I haven't changed anything in my snapd settings.

```
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=fr_FR.UTF-8
DISPLAY=:0
GNOME_SHELL_SESSION_MODE=ubuntu-communitheme
COLORTERM=truecolor
DESKTOP_AUTOSTART_ID=10fc46029313973407152412064688574600000013050007
USERNAME=hugop
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=2
USER=hugop
DESKTOP_SESSION=ubuntu-communitheme-snap-wayland
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
WAYLAND_DISPLAY=wayland-0
GTK2_RC_FILES=:/snap/communitheme/current/share/themes/Communitheme/gtk-2.0/gtkrc
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/02d9c686_12ff_43ee_ab45_00a707175e1c
PWD=/home/hugop
HOME=/home/hugop
TEXTDOMAIN=im-config
XDG_SESSION_TYPE=wayland
XDG_DATA_DIRS=/usr/share/ubuntu-communitheme-snap-wayland:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=ubuntu-communitheme-snap-wayland
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=5201
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=communitheme:ubuntu:GNOME
GNOME_TERMINAL_SERVICE=:1.52
XDG_SEAT=seat0
SHLVL=2
GDMSESSION=ubuntu-communitheme-snap-wayland
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=hugop
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu-communitheme-snap-wayland:/etc/xdg
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
SESSION_MANAGER=local/hugo-Dell:@/tmp/.ICE-unix/1305,unix/hugo-Dell:/tmp/.ICE-unix/1305
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/env
```

**Comment by Feichtmeier** [comment]
Maybe a wayland problem? I did  not log into it since ages

**Comment by Huluti** [comment]
You're right, I just tried with xorg, the problem does not happen ...

**Comment by didrocks** [comment]
Can you print the env with the second login? You have something missing in XDG_DATA_DIRS, but then, I can't understand why it would work the second time now :)

**Comment by Huluti** [comment]
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=fr_FR.UTF-8
DISPLAY=:0
GNOME_SHELL_SESSION_MODE=ubuntu-communitheme
COLORTERM=truecolor
DESKTOP_AUTOSTART_ID=10197aee6d3c023428152412165183970400000026320007
USERNAME=hugop
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
MANDATORY_PATH=/usr/share/gconf/ubuntu-communitheme-snap.mandatory.path
XDG_SESSION_ID=4
USER=hugop
DESKTOP_SESSION=ubuntu-communitheme-snap-wayland
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
WAYLAND_DISPLAY=wayland-0
GTK2_RC_FILES=:/snap/communitheme/current/share/themes/Communitheme/gtk-2.0/gtkrc:/snap/communitheme/current/share/themes/Communitheme/gtk-2.0/gtkrc
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/a1206d1b_e519_49bf_a4ff_2b8638e930c6
DEFAULTS_PATH=/usr/share/gconf/ubuntu-communitheme-snap.default.path
PWD=/home/hugop
HOME=/home/hugop
TEXTDOMAIN=im-config
SSH_AGENT_PID=1398
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=wayland
XDG_DATA_DIRS=/usr/share/ubuntu-communitheme-snap-wayland:/usr/share/ubuntu-communitheme-snap:/usr/share/ubuntu-communitheme-snap:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/snap/communitheme/current/share/:/snap/communitheme/current/share/
XDG_SESSION_DESKTOP=ubuntu-communitheme-snap-wayland
GTK_MODULES=gail:atk-bridge
WINDOWPATH=2
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=5201
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=communitheme:ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.59
XDG_SEAT=seat0
SHLVL=2
GDMSESSION=ubuntu-communitheme-snap-wayland
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=hugop
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu-communitheme-snap-wayland:/etc/xdg/xdg-ubuntu-communitheme-snap:/etc/xdg/xdg-ubuntu-communitheme-snap:/etc/xdg
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
SESSION_MANAGER=local/hugo-Dell:@/tmp/.ICE-unix/2632,unix/hugo-Dell:/tmp/.ICE-unix/2632
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/env

**Comment by Huluti** [comment]
This is fixed thank you very much! :tada:

**Comment by didrocks** [comment]
yw! ;)

**Comment by Huluti** [comment]
But some applications aren't themed anymore now like FileZilla, Atom,...

**Comment by didrocks** [comment]
snap applications? check https://github.com/ubuntu/gtk-communitheme/issues/325

**Comment by Huluti** [comment]
No filezilla from the repos
![capture du 2018-04-20 14-53-12](https://user-images.githubusercontent.com/5782198/39051941-90585462-44aa-11e8-81a4-a89cf47e99b3.png)

**Comment by didrocks** [comment]
something to submit as a separate bug against gtk-communitheme I guess…
