### ISSUE TITLE
Remove all colors used in _common.scss from _ubuntu-colors.scss and replace them with colors from _colors.scss

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#108]
I did this wrong in some commits -> I need to correct this soon.

**Comment by Feichtmeier** [comment]
@clobrano @godlyranchdressing 
I was thinking about this "issue" a lot lately. I think there are so many colors in _colors that I mostly can't know from their variable names what they look like. Ofc the IDE helps there but the color names from _ubuntucolors just jump into my mind. 
Most color variables get altered my lighten/darken/transperentize anyways so what's the point of having to many variables if they are just iterations of the ubuntu colors? =]

**Comment by clobrano** [comment]
I find easier to read a variable name than an expression and also to use the same percentage of change

**Comment by Feichtmeier** [comment]
Mostly fixed from my side.
