### ISSUE TITLE
Add hover-effect on desktop-selection

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#111]
When you choose a different desktop the UI gives you **no visual feedback when you hover** over different workplaces (note the mouse-cursor in screenshot).
Every other element which is clickable gives a visual feedback: It gets gray or brighter. In gnome-shell the windows you can select get a transparent-gray border. Maybe here the same should be used? Or the desktop gets slightly brighter when hover. @madsrh maybe you have a better idea.
![bildschirmfoto vom 2018-04-18 18-40-52](https://user-images.githubusercontent.com/36449926/38946088-b49ae1d2-4338-11e8-927e-21521dbd9023.png)

**Comment by godlyranchdressing** [comment]
I tried, but I can't get it to work. This CSS does make the thumbnail preview entirely red:

`.workspace-thumbnails StBin { background: red; } `

So I tried with:

`.workspace-thumbnails StBin:hover { background: red; }`

But it doesn't do anything on hover. :man_shrugging:

**Comment by NusiNusi** [comment]
@Feichtmeier @nana-4 @clobrano maybe you have a solution?

**Comment by Feichtmeier** [comment]
Tried hover, too but it did not work neither :| I guess this is a wontfix or a cantfix seems like gnome-shell does not support it

**Comment by clobrano** [comment]
If it is not supported or hard to figure out how to do it, I am totally OK with leaving it as it is
