### ISSUE TITLE
Make orange border of selected/active desktop thinner

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#112]
At the moment the orange border is here the thickest. It should be as "thin" as in other parts of the theme. 2px i think. The color is strong enough so that it will be recognizable.
![bildschirmfoto vom 2018-04-18 18-40-52](https://user-images.githubusercontent.com/36449926/38946226-16d2b67c-4339-11e8-9717-3f5c65da20f5.png)
![shell3](https://user-images.githubusercontent.com/36449926/38946666-76dbb464-433a-11e8-907a-1cb8e937e037.png)

**Comment by godlyranchdressing** [comment]
@Feichtmeier I'm sorry. I started work on this before you self-assigned. :scream: 

Line style:

![line](https://user-images.githubusercontent.com/27529229/38948227-ef6c2ef0-430c-11e8-8bcc-11228ad8cbb6.png)

**Comment by Feichtmeier** [comment]
You should definitely pull @godlyranchdressing xD you miss the transparency of the overview and the workspace thumbnail :P
