### ISSUE TITLE
Refine ALT-Tab-Switching

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#113]
@madsrh here the screenshots from @Feichtmeier proposed in https://github.com/ubuntu/gtk-communitheme/issues/289

1.
![38945809-d3dd02b0-4337-11e8-8ade-396cae688c2e](https://user-images.githubusercontent.com/36449926/38946492-e48b390e-4339-11e8-9247-1637bfbc962b.png)

2.
![38945501-f283ab20-4336-11e8-84f4-2c1a56b743b8](https://user-images.githubusercontent.com/36449926/38946496-e8acdd8a-4339-11e8-8664-f8274df890b5.png)

3.
![38945478-e4f8b0fe-4336-11e8-9abd-427d907c4dd0](https://user-images.githubusercontent.com/36449926/38946501-ece0c768-4339-11e8-9e82-bbb94ad693d7.png)

@Feichtmeier Thank you for the screenshots. I like 2 and 3 the most.

**Comment by godlyranchdressing** [comment]
How about this? 

![test](https://user-images.githubusercontent.com/27529229/38948081-836a0bbe-430c-11e8-8c5b-b2691f3725e9.png)

**Comment by Feichtmeier** [comment]
That's also option. But how do you fix the problem of cutting of the label? You need to turn off the extension to see that though :)

**Comment by godlyranchdressing** [comment]
@Feichtmeier screenshot? I don't get any issues on my side with and without the extension (which I always forget is an extension). 

I'm still using 17.10/GNOME 3.26 if that might be related to the issue.

**Comment by Feichtmeier** [comment]
@godlyranchdressing 
![peek 2018-04-18 20-30](https://user-images.githubusercontent.com/15329494/38950957-5da4370c-4347-11e8-8b61-34014a55d0ac.gif)
The label is getting cut of by the border and so changes in length

**Comment by Feichtmeier** [comment]
Yup also in your version:
![peek 2018-04-18 20-36](https://user-images.githubusercontent.com/15329494/38951254-56bac31a-4348-11e8-8987-5f519395a894.gif)
@godlyranchdressing but I absolutley love the idea of the small border and the light bg. :+1: 
@madsrh are you okay with the design? We'd merge then

**Comment by madsrh** [comment]
> How about this?

![image](https://user-images.githubusercontent.com/3986894/38951211-33be4d8c-4348-11e8-9355-aa198354b2b1.png)


@Feichtmeier @godlyranchdressing Yes! 👍 Actually I would say all of these suggestion are better suggestion than the current. As @NusiNusi would say: a much more elegant use of orange 😉

**Comment by madsrh** [comment]
I like the current one, but couldn't help but wonder if it could work without the orange border? Like when you hover headerbar items 🤔 

![image](https://user-images.githubusercontent.com/3986894/38960499-128caf4c-4365-11e8-86a8-8e07d49d2794.png)

**Comment by madsrh** [comment]
@godlyranchdressing @Feichtmeier What do you think about this?

**Comment by clobrano** [comment]
I'd rather have the one poste above by @madsrh or only the underline orange one. Both orange and background looks to much to me

**Comment by madsrh** [comment]
@clobrano You've got mail (or a hub PM) 😉

**Comment by Feichtmeier** [comment]
This is still my fav, since nusis elegance-offensive corrupted my mind xD
![peek 2018-04-26 09-56](https://user-images.githubusercontent.com/15329494/39293041-2549af26-4938-11e8-9ef7-53e7018cb6dd.gif)

**Comment by madsrh** [comment]
That looks good too @Feichtmeier. That will be my second favorite 😄

**Comment by madsrh** [comment]
I'm a bit lost here 😕 

https://github.com/ubuntu/gnome-shell-communitheme/commit/58dc4bf43e729146ea9586765c6636913a0c79e7

**Comment by Feichtmeier** [comment]
Ha! Nice code initiative!
Tbh, I've tried your mockup and you are right imho, this looks best:
![screenshot from 2018-04-26 10-10-16](https://user-images.githubusercontent.com/15329494/39293765-0c8ae214-493a-11e8-95cf-dce651f39f8a.png)
![screenshot from 2018-04-26 10-10-16](https://user-images.githubusercontent.com/15329494/39293789-1e21e932-493a-11e8-8ba8-3b189c65acf7.png)

______

What are you lost at? A decision or css knowledge?

**Comment by madsrh** [comment]
This is my first code. Is this the right way to do it? Shouldn't there be a pull request instead?

**Comment by Feichtmeier** [comment]
@madsrh yes when you are finnished with your commits make a PR even after you can commit until your branch is merged

**Comment by madsrh** [comment]
@Feichtmeier This is very much a minor tweak, but could you change the text color so only the selected item is white?

![image](https://user-images.githubusercontent.com/3986894/39452447-9a35e3a2-4cd2-11e8-96ca-e93c1210c397.png)

**Comment by Feichtmeier** [comment]
Sure - could you check this here then I make a PR for both:

I wanted to make the overview thumbnails (right panel in overview where you see the workspaces) and the search entry (which is currently solid) to have the same transperency carlo made the top panel use. This is the result:
![screenshot from 2018-04-30 23-56-26](https://user-images.githubusercontent.com/15329494/39452549-e02bd95c-4cd2-11e8-9c16-01f46ce02b28.png)

**Comment by Feichtmeier** [comment]
@madsrh 
![peek 2018-05-01 00-05](https://user-images.githubusercontent.com/15329494/39452708-7b3c3bb2-4cd3-11e8-8061-f7dfc22f39d8.gif)
