### ISSUE TITLE
Refine active apps in shell

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#114]
@madsrh proposed these ideas in https://github.com/ubuntu/gtk-communitheme/issues/289:

1. Using a dot like in the dock
2. Using a longer underline

![shell2](https://user-images.githubusercontent.com/36449926/38946602-43a4e2c8-433a-11e8-8360-b0c4ee3e64bb.png)

**Comment by Feichtmeier** [comment]
Hmmmmm... I am not sure if this would look good. I would rather say increase the lenth of the line because at the moment one does not even recognize it

**Comment by madsrh** [comment]
![untitled-2](https://user-images.githubusercontent.com/3986894/38962752-05bd66ee-436f-11e8-9bb6-87e83f3c324b.gif)

**Comment by NusiNusi** [comment]
The dot is used in the dock too for active app. But the difference is that the dots give you information about the **number of active windows**:
![bildschirmfoto von 2018-04-19 18-41-12](https://user-images.githubusercontent.com/36449926/39005862-9d40bb64-4401-11e8-9062-acdc801714f1.png)

So i think dots should be used only for that purpose. It would look strange when you see three dots in the dock and only one dot in the app-viewer (is that the name?) of the shell. I recommend using the longer underline. The underline is already used for "active" and "selected" and would mean in this situation that this app is "active". What do you think?

**Comment by madsrh** [comment]
I think the best looking one is the dot to the left side of the label, but you're right @NusiNusi that the line would be consistent with pathbar, menubar, ...

**Comment by clobrano** [comment]
Consistent but possibly misunderstandable. A sign between to icons might be associated with both icons on top or below. Moreover, if the dock is at the bottom, the underline would either clash with dots (if put below the icon) or would stop being an underline (if put on the right side)

**Comment by Feichtmeier** [comment]
We could just leave it as it is

**Comment by madsrh** [comment]
> ...if the dock is at the bottom, the underline would either clash with dots (if put below the icon) or would stop being an underline (if put on the right side)

@clobrano You lost me! Are you talking about the dock? This issue is for the application overview.

**Comment by clobrano** [comment]
Oops, sorry, I misunderstood.

**Comment by Feichtmeier** [comment]
![screenshot from 2018-04-23 14-31-25](https://user-images.githubusercontent.com/15329494/39126549-079dfc84-4703-11e8-943e-0ac79332c6e9.png)

  .app-well-app-running-dot { //running apps indicator
    width: 40px; height: 3px;
    background-color: $selected_bg_color;
    margin-bottom: 2px;
  }

**Comment by madsrh** [comment]
@Feichtmeier Would it be possible to move the dot to the left side of the label (as the mockup above)? If not, I would go with the line or maybe even the current short line 😮

**Comment by Feichtmeier** [comment]
@madsrh I fear not. It seems like there is basically a grid which is exactly 1 more row for each icon. And that additional row is placed under the icon and can contain stuff (like a background or an icon). And it's placed under the big application icon

**Comment by ya-d** [comment]
I'm not around here very often recently, but it's always great to see your progress! 👍 

Active apps are already indicated in the dock which is always visible besides the app overview. So I would say skip dots/lines completely and treat all apps equally: show a plain grid of all installed apps. That's what overview is for. Running apps (and favorites) are shown in the dock.

(Underlines everywhere else have a different meaning too: they indicate _one_ selected/open element.)

**Comment by madsrh** [comment]
👍 As much as I agree with you @ya-d, I'm not sure we can simply hide the _running apps line/dot_ as this is a upstream design decision.

**Comment by clobrano** [comment]
Hi @ya-d thank you!

> So I would say skip dots/lines completely and treat all apps equally: show a plain grid of all installed apps. That's what overview is for. Running apps (and favorites) are shown in the dock.

I think we shouldn't remove upstream functionalities, as we did with panel transparency in gnome-shell

**Comment by clobrano** [comment]
Maybe gnome help is just out of date :) but, replacing an icon with another is not the same as removing it.

**Comment by Feichtmeier** [comment]
So we agree that we leave it as it is?

**Comment by clobrano** [comment]
I actually prefer the dots, even below the icons, maybe just a little bit more detached from the icon, like in the dock. Would it be possible?

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/39187234-0b28fee2-47cd-11e8-8173-98391d668259.png)

margin-bottom: 2px
margin-top: 5px

**Comment by clobrano** [comment]
> But the dots are already used for the number of active windows.

Sorry, but I don't see the problem

> But the margin gets capped somewhere.

Yeah, I made it adjusting margin-top by ~200px :grinning: but it messed up with the dock (no sure why) and didn't find a simple way to avoid it. However, as below it looks nice, what do you think?

    .app-well-app-running-dot {
        width: 7px; height: 7px;
        border-radius: $small_border;
        background-color: ...
        margin-bottom: 0;
    }

**Comment by Feichtmeier** [comment]
Looks good
![image](https://user-images.githubusercontent.com/15329494/39191680-c04da688-47d7-11e8-8f0d-cd3985822635.png)

**Comment by NusiNusi** [comment]
> Sorry, but I don't see the problem

I explained a few post up:

> The dot is used in the dock too for active app. But the difference is that the dots give you information about the number of active windows. So i think dots should be used only for that purpose. It would look strange when you see three dots in the dock and only one dot in the app-viewer (is that the name?) of the shell.

You will confuse the user. He is going to see three dots on the left for three opened nautilus-windows and just one dot in the shell. By the way the orange in the shell gives you information about **active apps**. the theme uses **always lines for active elements**. Using dots would be completely inconsistent.

I see really no rational reason for using dots and recommend keeping it how it is or using a bigger underline.

**Comment by clobrano** [comment]
> I see really no rational reason for using dots

The gnome shell uses dots to represent active applications. The dock is able to count them, dash doesn't, but the user knows it still an indication of an active application.

**Comment by Feichtmeier** [comment]
@NusiNusi I don't think it's that confusing. But I really don't care that much about this part of the shell because both versions work, = P

What about this (this is closer to one of mads mockups)
![screenshot from 2018-04-24 16-28-43](https://user-images.githubusercontent.com/15329494/39193829-a75bcc2c-47dc-11e8-8b56-0a84dfafcfb1.png)

**Comment by clobrano** [comment]
Underline is used often as selection indicator, more than active, this is the reason I would prefer the dots

**Comment by madsrh** [comment]
@Feichtmeier Do you have a PR for this _dot_ version so we could try it? (that snap thing is such an awesome tool 💪 )

![image](https://user-images.githubusercontent.com/3986894/39215763-5e6747ac-4819-11e8-8a12-3d7210a0af0a.png)

**Comment by Feichtmeier** [comment]
There it is =)

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/gnome-shell-communitheme/pull/149#issuecomment-385417744
