### ISSUE TITLE
Some shell buttons are not flat

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#119]
I just realized that @luxamman 's design is still on the todo list:
https://community.ubuntu.com/t/mockups-new-design-discussions/1898/250

**Comment by madsrh** [comment]
@godlyranchdressing you're already on a roll with the buttons 😉

**Comment by Feichtmeier** [comment]
He is doing the gtk buttons. After a tip I received from carlo I can do this flat shell buttons! There are actually not very much left. I already changed the button in the message menu to flat. Whats left? Would be nice if you help me gather all the shell buttons. I remember the cancel button in the login screen... and that's it :grinning:

**Comment by Feichtmeier** [comment]
![screenshot from 2018-04-28 01-42-42](https://user-images.githubusercontent.com/15329494/39389082-8130682c-4a85-11e8-9fe8-d76f96c2c220.png)
![screenshot from 2018-04-28 01-42-34](https://user-images.githubusercontent.com/15329494/39389083-8149c380-4a85-11e8-869c-47fdc68ceb8e.png)
Not flat.
