### ISSUE TITLE
Arrange windows in active-windows

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#120]
I am pretty sure i am using the wrong terms here. So feel free to change the title. At the same time i am not so sure if this is intended:
![bildschirmfoto von 2018-04-19 19-49-20](https://user-images.githubusercontent.com/36449926/39009186-3c22f2d4-440b-11e8-89e6-7d492ec3b3d6.png)
On the screenshot you can see that the windows (nautilus) are arranged to the left and not in the middle of the gray background. IMHO this looks broken. They should be arranged to the middle and not to the left. I hope you could understand what i mean.

**Comment by madsrh** [comment]
![12](https://user-images.githubusercontent.com/3986894/39020890-c0903c48-442e-11e8-97ca-f950540bceb0.gif)

**Comment by godlyranchdressing** [comment]
I think this is related to another issue I found. Popover menu items are centered in the system menu and if a menu item is long (like a VPN connection name) then it gets truncated so much that you can't see more than a couple characters.

![aa](https://user-images.githubusercontent.com/27529229/39057756-0dbbf1ac-4488-11e8-994c-46471840e491.png)

**Comment by Feichtmeier** [comment]
I wonder weither this is more a dash to dock upstream issue?
Adapta has the same problem:
![screenshot from 2018-04-30 15-14-31](https://user-images.githubusercontent.com/15329494/39428867-42099fc8-4c89-11e8-8ae0-81247db2def7.png)
Materia has the same problem:
![screenshot from 2018-04-30 15-14-41](https://user-images.githubusercontent.com/15329494/39428875-481d28da-4c89-11e8-8dd0-2b38f313cff4.png)

**Comment by Feichtmeier** [comment]
Closing this as this is not really related to this theme but rather to dash to dock
