### ISSUE TITLE
Background selection became blue

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gnome-shell-communitheme#124]
I might have missed the discussion, but my understanding is that selection on the third picture in the first row should be orange

![image](https://user-images.githubusercontent.com/2883614/39130329-168fb4a8-470d-11e8-8513-3ded080d1223.png)

**Comment by Feichtmeier** [comment]
Uhh? is this the current master? This is mine:

![image](https://user-images.githubusercontent.com/15329494/39130481-762b0192-470d-11e8-8753-a3b2001a699d.png)

(((But this is the wron repo xD)))

**Comment by clobrano** [comment]
> (((But this is the wron repo xD)))

My bad! Before moving the issue, let me try with a fresh master

**Comment by NusiNusi** [comment]
It's blue here too. I like it but it is way too light. Not sure if this was intended by @godlyranchdressing

**Comment by clobrano** [comment]
Closing it here since it is the wrong repository
