### ISSUE TITLE
Slider consistency part II

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#132]
Consistency-police found this:
gtk
![peek 2018-04-26 17-30](https://user-images.githubusercontent.com/36449926/39315866-04aebbb8-4978-11e8-84e9-20d0cfe6947e.gif)
(blue border on hover (1px?) and stronger blue border when clicked (2px?))

gnome-shell
![peek 2018-04-26 17-32](https://user-images.githubusercontent.com/36449926/39315882-0e678932-4978-11e8-87e3-1b12d117033d.gif)
(nothing)

Should the gnome-shell-slider get a blue border when hover like in gtk and a thicker blue-border when clicked? Is this even possible?

And this is for @madsrh and @Feichtmeier : could the border around the round slider become orange on hover/click instead of blue? because it is "selected". Tried a mockup and it looks very bad. Maybe you could make a better one when this idea is worth following.

**Comment by Feichtmeier** [comment]
Yup, tried a lot there - sadly there is no property for neither the border or the color of the handle (circle) :/
But I would not remove the blue hover on the gtk theme because it looks good on bright backgrounds. I guess we have to live with that

**Comment by Feichtmeier** [comment]
Maybe @nana-4 or @godlyranchdressing know how this works. Nana managed to change the color atleast on materia
![screenshot from 2018-04-26 18-06-33](https://user-images.githubusercontent.com/15329494/39317728-9454f5da-497c-11e8-8a59-720d921f3ca0.png)

**Comment by NusiNusi** [comment]
Oh this screenshot fired my desire for white shell-popovers... :heart_eyes:

**Comment by godlyranchdressing** [comment]
@Feichtmeier there's an unused property I found somewhere in the Shell's source files that should let us change the border color. I'll see if I can find it again.

**Comment by Feichtmeier** [comment]
@godlyranchdressing yup that was what I've found too but this does not work :disappointed:

**Comment by Feichtmeier** [comment]
@godlyranchdressing well atleast this works:
![screenshot from 2018-04-28 01-34-17](https://user-images.githubusercontent.com/15329494/39388965-4d348612-4a84-11e8-9991-470c9975f39a.png)
If your CSS magic allows some kind of circular box shadow? Other than that the shell is just a bit more flat than the gtk theme so I don't see a big problem here to be honest!

**Comment by Feichtmeier** [comment]
Not possible currently - closing
