### ISSUE TITLE
Add soft transition for hover over all clickable elements in popover

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#133]
This is finetuning and has no priority. But i think we could start adding animations and soft transitions. They are already there but not for every clickable element:
![peek 2018-04-26 19-45](https://user-images.githubusercontent.com/36449926/39322638-d6aa2302-498a-11e8-9c33-c0431b10f56b.gif)

@Feichtmeier if it is too early to work on this we can close this and i come back later (i surely won't forget :gun:)

**Comment by Feichtmeier** [comment]
No let's keep it open until we have either a solution or a wontfix - I fear that the shell might be very limited at this but let's see

**Comment by Feichtmeier** [comment]
I tried some things but this is not possible we could only decrease the transition time which makes it look sluggish and slow. So this is a wontfix to me  - @madsrh @clobrano feel free to close this if you agree
