### ISSUE TITLE
Change close button

### ISSUE THREAD

**Issue by Ads20000** [ubuntu/gnome-shell-communitheme#138]
Currently the close button is an orange circle within a grey squircle (when hovered over). This seems strange to me (especially given the close button for windows in Activities is just the orange circle). Perhaps, instead, could the close button be just an orange squircle when hovered over (and could the Activities close button also be an orange squircle)? Or maybe it should just be a grey rounded square / squircle like the Firefox close tab button...

Current:
![screenshot from 2018-04-27 19-09-26](https://user-images.githubusercontent.com/3178485/39378636-eaf53114-4a50-11e8-8af2-81c45ca6a7f4.png)
![screenshot from 2018-04-27 19-08-56](https://user-images.githubusercontent.com/3178485/39378637-eb17fa14-4a50-11e8-96be-56930fe2da00.png)

<details>
<summary>Communitheme 0.1 (124)</summary>

```
$ snap info communitheme
tracking:  edge
refreshed: 2018-04-27T12:53:08+01:00
installed:   0.1 (124) 6MB -
$ snap version
snap    2.32.5+18.04
snapd   2.32.5+18.04
series  16
ubuntu  18.04
kernel  4.15.0-20-generic
$ snap info core
tracking:  beta
refreshed: 2018-04-16T11:33:06+01:00
installed:   16-2.32.5                (4486) 90MB core
```

</details>

**Comment by Feichtmeier** [comment]
There is some hot discussion going on on the gtk-theme repo about this:
https://github.com/ubuntu/gtk-communitheme/issues/369
Please post your first post there! :) Best regards!
