### ISSUE TITLE
Make the use of blue consistent

### ISSUE THREAD

**Issue by Ads20000** [ubuntu/gnome-shell-communitheme#141]
This needs design but I think the general use of blue needs some sort of policy that is consistently adhered to. Currently it's used in some sliders, the battery % bar in Settings, the cursor loading icon, and I think the Software loading icon? Is the intended use of blue for non-attention-grabbing indication? In which case shouldn't quite a lot of things be blue (Firefox tabs, Firefox Awesome Bar, pips in the Dock, lines in Activities, text selection...)? I complained about the Firefox tabs and Awesome Bar being blue but maybe that is just more consistent if it's being used in the indication sense...or maybe anything that seems fundamental to Ubuntu could be orange which includes Shell elements (but then Shell (top-right system menu) sliders should be orange?) and.perhaps also web browsers ... but maybe that's not fundamental to Ubuntu per se.

My thinking on this is very confused and perhaps this Issue needs breaking down but I thought there needed to be some meta-Issue on the general usage of blue so that it can be made consistent! :)

**Comment by NusiNusi** [comment]
text: black, white
background: gray, dark gray, white
selected/active: orange
radiobuttons/checkmarks: green
progress/slider: blue

**Comment by Feichtmeier** [comment]
I do not see many inconsistencies tbh (there was a very long design discussion on the community hub)
Only the selection seems a bit inconsistent since we changed the nautilus sidebar. 
Now we have the vertical stripe selection, orange selection and grey selection in treeviews :-1: 
Before we had orange, orange and orange (very orange but also very consistent) =)
But we can discuss all kind of things here, too. Why not?

**Comment by febcrash** [comment]
I propose to use the ubuntu **purple** rather than blue that reminds of GNOME Vanilla for sliders and progress bars.

**Comment by Ads20000** [comment]
Purple is Canonical's colour which is used in desktop backgrounds (with the orange) but pretty much nowhere on the desktop other than that. Blue was used in Suru, Unity 8's desktop, which this theme is taking inspiration from.

**Comment by Feichtmeier** [comment]
The blue is also very different from the adwaita blue

**Comment by Feichtmeier** [comment]
While we appreciate the general discussion we have a pretty clear vision now, revert back to orange on everything execpt volume sliders and progress bars. So I guess we can close this, @madsrh ?

**Comment by Ads20000** [comment]
But what's the justification for having blue volume sliders and progress bars? Could you link the justification here and then close? :)

**Comment by madsrh** [comment]
@Ads20000 It came from the Unity8 design
https://www.behance.net/gallery/51029335/Ubuntu-System-Indicators

As @Feichtmeier mentioned, the colors are being adjusted, but blue is still there. If there's inconsistencies we should of course fix them 👍

**Comment by Ads20000** [comment]
Apologies if I'm being irritating but isn't there some Unity 8 / Suru design docs somewhere? I.e. why did they choose to use blue for those things and did they not use blue anywhere else? I'd quite like to know the written justification and whether using blue for progress bars and sliders is consistent with that justification or not :)

**Comment by madsrh** [comment]
@Ads20000 You'll find that we don't use blue the same way Canonical did here - we simply cherry picked what we liked, but you asked where the blue came from 😃 Canonical also iterated their design to use a different blue.

https://docs.google.com/document/d/1CjPvxz_dk9Cn5HiZ_d0POYtqNAHjO1c5omAbNjZJiKg319
https://docs.google.com/presentation/d/1FtHFW67ycl6uvxZqKIZwyinVyOuV9NxXDuJv1SwQ70k124
https://docs.google.com/document/d/1Ami5HfKQFmFqmJGSdYQmCidv1T4NPM3ecJL3y3PvyWs92
https://docs.google.com/document/d/1Pd3ORoNlH7SAU9zkxKg3-0VdxhWXwcgS-bsPteCQhiw83
https://docs.google.com/presentation/d/1sDY1dT31v7vTmYQmJNMkwG9PNjLj3RAwwrlKm2aV3z054
https://docs.google.com/presentation/d/1tpH-vtedGBcvxq-cEgJfAY4XsuHluYdH32yZjYqnU4877
https://docs.google.com/presentation/d/1sAUF2qWIblYqTtkQe5iI4d75QLtEJNjpYNaww6kPViM

**Comment by Feichtmeier** [comment]
If I take a look a the whole desktop it really makes sense to me and (personal opinion) looks really beautiful with the blue:
![screenshot from 2018-05-01 08-45-03](https://user-images.githubusercontent.com/15329494/39464153-17e1018a-4d1c-11e8-9aaa-9fa0eebc7dbe.png)

**Comment by madsrh** [comment]
I tried to remove the blue from the sliders, but it kind of dull.

![slider](https://user-images.githubusercontent.com/3986894/39464691-36cc2db0-4d1f-11e8-828c-1cb6a98d2385.jpg)

**Comment by madsrh** [comment]
Speaking of blue inconsistencies - It makes no sense that the progressbar in the dock is gray/white.

![image](https://user-images.githubusercontent.com/3986894/39465272-b6fd1cbc-4d22-11e8-8c10-303b7cd9d52f.png)

@Feichtmeier If you agree, could take fix that? (we don't need a new issue, right?)

![image](https://user-images.githubusercontent.com/3986894/39465202-585f754c-4d22-11e8-86e6-1d92e8bee5e1.png)

**Comment by Feichtmeier** [comment]
Oh nice find! I'd try this (it's shell after all - so the chance of my success is pretty high =O)

**Comment by mivoligo** [comment]
There's also blue used for the background of selected text. Not sure if bug or feature.

**Comment by Ads20000** [comment]
I think that's a bug? It's orange for me in Firefox (Deb) but blue in Mailspring (snap), for example.

**Comment by mivoligo** [comment]
I've noticed blue in Gedit and blue when renaming files in Nautilus

**Comment by madsrh** [comment]
@Ads20000 @mivoligo We tried blue for a while ([like Unity8](https://www.behance.net/gallery/9167887/Ubuntu-System-and-Contextual-Menus)) but have just recently returned to orange.

@Ads20000 are you okay with me closing this issue?

**Comment by Ads20000** [comment]
@mivoligo There's no blue in Text Editor 3.28.1 (in Ubuntu 18.04) on the Communitheme edge snap, nor in Files.

@madsrh The Dock progress bar issue could be filed separately from this one... I get 'Sorry, the file you have requested does not exist.' for the first six links you shared with me Mads (thanks for posting those!), do the sharing permissions need to be adjusted (if that's OK)?

By saying 'Make the use of blue consistent', really what I was asking for was an underlying justification for the use of blue in the progress bars and sliders rather than just 'it looks nice' - what's the purpose of it? Orange is the Ubuntu brand colour; black, white, grey are background colours... Maybe it's just for a bit of diversity and the only justification is that 'it looks nice' (and was used in Unity 8 for this and a few other things), I notice that the bullet selections in the Files context menu are green so maybe a smattering of other colours in the theme is OK... hmm...

**Comment by Feichtmeier** [comment]
It's not only that I like blue, everyone loves i t! =) Or atleast many. It looks fresh it is a special blue and it spices up the black/orange in ubuntu. We had this discussion before on the community hub.
The use is now "consistent" so we can close this. But I feel that this is rather a rant about the blue sliders ;O Anyways, thanks for reporting issues

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/gnome-shell-communitheme/issues/157 new issue for the dock progress bars

**Comment by Feichtmeier** [comment]
Oh it was everywhere :D just search for blue in the big theme thread
![image](https://user-images.githubusercontent.com/15329494/39482342-f08372c8-4d6e-11e8-9a3c-4b521385dc0f.png)

**Comment by Ads20000** [comment]
For future reference:
@didrocks [provided the Ubuntu Touch colour palette](https://community.ubuntu.com/t/mockups-new-design-discussions/1898) ([as did Andrew Keech](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/55?u=ads20000))
The blue on the sliders was raised [back in January](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/268?u=ads20000) as looking like you 'forgot to theme' it so my Issue is a duplicate I'm sorry! In reply to that, @madsrh [said](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/271?u=ads20000) 'Very good point with the volume slider (I had the same feeling), but I think that when/if the rest of the UI elements also used blue (Unity8)23, it wouldn’t feel this way.' but now the blue is only used for sliders and progress bars? And then there's a lot more discussion that I'll need to get round to reading at some point to see if there's any loose ends...

**Comment by godlyranchdressing** [comment]
@Ads20000 there's also [this](https://design.canonical.com/2016/05/colour-palette-updates/) blog post behind the use of blue.
