### ISSUE TITLE
Increase window clone border's transparency 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#142]
![screenshot from 2018-04-28 09-59-37](https://user-images.githubusercontent.com/15329494/39393878-f31eb64c-4aca-11e8-9288-599ed8883c49.png)

By 5%
![screenshot from 2018-04-28 09-58-28](https://user-images.githubusercontent.com/15329494/39393879-f3432b3a-4aca-11e8-9e9c-cb7b8d7f49b3.png)

@madsrh okay? A little bit looks more like what we wanted to achieve in the first place

**Comment by madsrh** [comment]
+1 looks good @Feichtmeier
