### ISSUE TITLE
Notificationdot in shell-topbar could be misleading

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#144]
![notificationdot](https://user-images.githubusercontent.com/36449926/39394783-539e7dbc-4ad6-11e8-8314-80d7de8b2a70.png)
Until yesterday i thought this dot represents the sun and is some kind of a weather-notification. Never clicked on it because of this.
I know this is upstream and the dot will stay. But could it get some color? Let's say blue? To give it more a notification-character? Is this even possible to colorize it without influencing the text-color?

**Comment by Feichtmeier** [comment]
Yeah that would be straight against upstream, I actually had a discussion about this (where I was a bit over emotional) with one of the official gnome guys 1 day after switching away from unity in 17.10 beta :dancer: 
It took quiet some time for me to realize two things:
- this dot is the unread notification icon
- this dot only appears after either four regular or 1 very important notification

The right place to change this would be the icon theme.
For example the awesome icon theme la-capitaine makes it look like this:
![image](https://user-images.githubusercontent.com/15329494/39395257-c9c5bad6-4adc-11e8-9b35-dd275e804e30.png)
![image](https://user-images.githubusercontent.com/15329494/39395264-dffa3782-4adc-11e8-8317-382760829932.png)
