### ISSUE TITLE
Communitheme option don't seem to be avaliable

### ISSUE THREAD

**Issue by SemnoSao** [ubuntu/gnome-shell-communitheme#146]
I've installed the snap package but when I restart I don't have the communitheme session option, it doesn't show up even among themes in the tweak tools app

**Comment by SemnoSao** [comment]
i've installed via ppa and now it worked properly

**Comment by didrocks** [comment]
Have you read properly the instructions on blog post or associated to the snap? You need to logout and select the communitheme session. The communitheme theme will never appear via the snap on the regular ubuntu session.

**Comment by SemnoSao** [comment]
Yeah, and that's the problem. Communitheme session option on the logon screen wasn't there. I logged off, restarted the computer and it wouldn't apper. So I uninstalled the snap and installed via ppa, logged off and it was there properly

**Comment by Feichtmeier** [comment]
Have you had the ppa installed before the snap and then installed then snap "over" the ppa version?
___
It's actually pretty straight forward - used this myself on my families computers (private test area ;O):
- fresh ubuntu 18.04 installation
- install the theme by either from within the terminal or gnome software
- RESTART
- select the communitheme session (shell is now themed correctly and suru icon theme should be selected)
- open tweaks and select the GTK theme

That worked all the time for me - I really think you did something wrong :(

**Comment by Feichtmeier** [comment]
Just installed the theme yet again on one more family pc after a fresh 18.04 install and other than the disturbing GDM3 bug, I did not encounter any problems you described @SemnoSao
