### ISSUE TITLE
Communitheme icons broken?

### ISSUE THREAD

**Issue by paulorenatoxs** [ubuntu/gnome-shell-communitheme#147]
Hello. I've just installed the communitheme on 18.04. Everything works minus the icons (see screenshot for reference)
Any hints as to why this is happening? Could the GNOME Tweak Tool be inferring in some way?
https://imgur.com/a/VJAaVj0

**Comment by Feichtmeier** [comment]
Did you log into the communitheme session?

**Comment by klingel** [comment]
Same here.
As for my part, I also logged into the communitheme session.

**Comment by Feichtmeier** [comment]
@didrocks any idea why this happens? What info should those two guys provide? =)

**Comment by machacjan** [comment]
Same here, after fresh install of Ubuntu 18.04 + Communitheme. I'm logged in Communitheme on Weyland, btw. At first I thought it was just me, and thought about uninstalling, but hey, thank god for GitHub. I'll try to provide whatever info needed.

**Comment by didrocks** [comment]
Are you sure you didn't change any defaults for icons, themes and such? Ensure that your gsettings keys are resetted if it's not the case.

I have a snap ready for to help resetting the defaults, but it's blocked on classic confinement adoption.

Meanwhile, you can run this on a terminal:
```sh
keys="/org/gnome/desktop/interface/cursor-theme /org/gnome/desktop/interface/icon-theme /org/gnome/desktop/interface/gtk-theme"
keys="$keys /org/gnome/desktop/sound/theme-name /org/gnome/desktop/sound/input-feedback-sounds"
keys="$keys /org/gnome/mutter/center-new-windows"

for k in $keys; do
    dconf reset $k
done
```

**Comment by machacjan** [comment]
@didrocks That did the trick for me, thanks!

**Comment by Feichtmeier** [comment]
@machacjan would be great if you could answer to weither to you changed anything to know if this is a communitheme related bug.

**Comment by machacjan** [comment]
Well, now that I looked into it a little further, I'm a bit confused as of what happened. As you can see in the following screenshots, when I select the "Communitheme" icons, directories show as blank files, but when I select the "Suru" icons, everything looks fine. Is this some kind of mix up on my end, or is this default behavior?

![screenshot from 2018-04-30 16-19-55](https://user-images.githubusercontent.com/15195851/39432312-6a660682-4c93-11e8-84f5-50486ce5f357.png)
![screenshot from 2018-04-30 16-20-33](https://user-images.githubusercontent.com/15195851/39432313-6a8bc7a0-4c93-11e8-8a89-c2afb8d750b1.png)

@Feichtmeier As to your inquiry of me changing anything, I'll try to be as precise as possible, though it was yesterday and I was doing other things at the same time, so it might not be 100% accurate. So, after installing Ubuntu 18.04 I installed the Communitheme package from Software center, and before I rebooted my machine I installed the Tweaks package as well and fiddled with themes. After the reboot I was not able to successfully start my Communitheme session (blank screen with just the cursor being shown and interactive). So then I tried the default session on Wayland, which worked, so I rebooted once again and tried my luck with Communitheme on Wayland, which worked as well, minus the icons issue. And that's it.

**Comment by Feichtmeier** [comment]
@machacjan thank you very much - maybe @didrocks can use this information - otherwise if it's invalid please close it didi

**Comment by klingel** [comment]
I experience the same behaviour as @machacjan illustrated above with screenshots.
I also installed the Tweaks package, but also installed pop-theme from ppa:system76/pop and _with this enabled_ I read about the communititheme and installed it. I saw broken icons and did a `ppa-purge ppa:system76/pop`. After that also tried some removing/installing of the communititheme snap as well as resetting the gsettings keys suggested by didrocks - no success.

I should also mention that I have ongoing problems to log into sessions _after a boot_ in general - starting with my 1st boot after fresh install:
1st try -> password incorrect
2nd try -> blank screen with just the cursor being shown. I can escape via ctrl+alt+f2 and get back via ctrl+alt+f1 which enables me to get a 3rd try
3rd try -> I can log in.

One question: Does the communititheme ship the "Suru" icons?
With "Suru" icons selected the theme looks also fine to me.

**Comment by didrocks** [comment]
@Feichtmeier: It's invalid. Most of people encoutering in one user session like gtk theme, icon theme or sound theme not set as default, no correct font size or settings like that are people who changed directly in gsettings or via some 3rd party tools like Tweaks their settings.

Hence the reset command given above. Something you can suggest for people is to create a new user and log into the session.

It seems as well that some people didn't read the installation instruction or blog post and didn't connect to the communitheme session (which is the only session the theme is made available).

@klingel: the login issue is a known gdm issue, not related to communitheme at all (you will have the same in the ubuntu session).

I'm thus closing this bug.

**Comment by klingel** [comment]
@didrocks Thank you for your hint to the known gdm issue :+1:

**Comment by Feichtmeier** [comment]
@didrocks could you point me to the gdm bug on launchpad?

**Comment by SemnoSao** [comment]
I tried the trick up there and it didn't fix it and made other themes I had stop showing properly ;-;
is there a way of undoing it ;-;
