### ISSUE TITLE
Not showing all tray icons

### ISSUE THREAD

**Issue by Alculete** [ubuntu/gnome-shell-communitheme#15]
when using tray icon not all tray icons of installed app appear. I have skype and dropbox installed and only appear if I'm using ubuntu section and not communitheme section

**Comment by clobrano** [comment]
Here the part of the discussion due on gtk-communitheme
https://github.com/Ubuntu/gtk-communitheme/issues/64

**Comment by clobrano** [comment]
Here the part of the discussion due on gtk-communitheme
https://github.com/Ubuntu/gtk-communitheme/issues/64

**Comment by Feichtmeier** [comment]
Yes this is exactly the same problem as https://github.com/ubuntu/gnome-shell-communitheme/issues/95
When you start skype with 
env XDG_CURRENT_DESKTOP=Unity skype
The indicator appears. The same as with dropbox. 
Hm I guess we need a global solution for this

**Comment by Feichtmeier** [comment]
I close this, links this in the dropbox issue (https://github.com/ubuntu/gnome-shell-communitheme/issues/15) and change that one to a general problem =) Thanks for reporting @Alculete

**Comment by Alculete** [comment]
OK, I will follow on the other issue. Thank you
