### ISSUE TITLE
Make the progress bars ubuntu blue 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#157]
![39465272-b6fd1cbc-4d22-11e8-8c10-303b7cd9d52f](https://user-images.githubusercontent.com/15329494/39480765-7a9c7942-4d69-11e8-878f-b041d493113a.png)
![39465202-585f754c-4d22-11e8-86e6-1d92e8bee5e1](https://user-images.githubusercontent.com/15329494/39480764-7a752b9e-4d69-11e8-8c75-0bd767ac7246.png)

**Comment by Feichtmeier** [comment]
@madsrh since we changed the counter in gnome software to green, should we change the badge counter in the dock a lso to green?
![screenshot from 2018-05-03 21-43-30](https://user-images.githubusercontent.com/15329494/39599124-110cca50-4f1b-11e8-8639-1df8c4c1d74e.png)

**Comment by madsrh** [comment]
@Feichtmeier That would make sense 🤔 but if so, we should use a darker green because there's not enough contrast with the white text.

**Comment by Feichtmeier** [comment]
@madsrh 
![image](https://user-images.githubusercontent.com/15329494/39599379-f7f85ccc-4f1b-11e8-8a04-0e284dbaeea4.png)
That's 5% darker, everything else darker looks like a Christmas tree

**Comment by Feichtmeier** [comment]
@madsrh borders are also possible:
![image](https://user-images.githubusercontent.com/15329494/39599581-75bdd1d2-4f1c-11e8-82e7-3a80a3fdf27b.png)

**Comment by madsrh** [comment]
@Feichtmeier What do you think of the 5% - too much? I do think the text is (although only slightly) easier to read.

Are shadow like this possible?
![image](https://user-images.githubusercontent.com/3986894/39602226-dae623f4-4f24-11e8-8c87-463f8768794d.png)

**Comment by Feichtmeier** [comment]
Holy crap yes box shadow also possible:
![screenshot from 2018-05-03 22-57-12](https://user-images.githubusercontent.com/15329494/39602421-694e99fa-4f25-11e8-8928-d203ba84d2e0.png)
![image](https://user-images.githubusercontent.com/15329494/39602422-6a5f1568-4f25-11e8-9492-fbdb2d5b1f38.png)

Yeah I would leave the green as is - it is perfectly readable imho

**Comment by Feichtmeier** [comment]
@madsrh I've chatted with the awesome @azzar1 who implemented the unity launcher API into dash to dock and he said that the progress bar is not theme-able at the moment but he could implement it when he has some spare time - so let's keep this issue opened so none else opens it

**Comment by Feichtmeier** [comment]
Migrated to the gtk repo
