### ISSUE TITLE
Some apps get full transparency window!

### ISSUE THREAD

**Issue by mgscreativa** [ubuntu/gnome-shell-communitheme#162]
As stated here https://askubuntu.com/questions/1029736/communitheme-transparent-windows-on-ubuntu-18-04 some windows get completely transparent, they are usable, but they shouldn't be transparent at all...

This is the calculator app...
![captura de pantalla de 2018-05-03 15-08-08](https://user-images.githubusercontent.com/1286632/39594708-d6b6c8ce-4ee3-11e8-84ba-21e8abd3973c.png)

System monitor app...
![visaa](https://user-images.githubusercontent.com/1286632/39594742-f3275136-4ee3-11e8-8ef8-4c4fa5434c46.png)

**Comment by Feichtmeier** [comment]
This is already fixed and should land in the stable channel soon:
https://github.com/ubuntu/gtk-communitheme/issues/325
Thanks for reporting, best regards
