### ISSUE TITLE
Orange close buttons on every window

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gnome-shell-communitheme#164]
I was testing pr #161 with `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr161`

I've noticed the close buttons on all open windows have orange background. IMHO it doesn't look to good when you have lots of windows opened or when you press 'super' key and hover over a window. In that situation you see 2 orange buttons next to each other (screenshot attached)

I don't know if this is the final design though.

![zrzut ekranu z 2018-05-04 11-16-15](https://user-images.githubusercontent.com/1629120/39624001-823587b6-4f8f-11e8-97c7-761f0408123a.png)

**Comment by Feichtmeier** [comment]
Yes there is an issue for this topic as a design discussion please post your opinion on there can't link ATM

**Comment by Feichtmeier** [comment]
Wait do you mean the close button in the gtk theme? Then there is an issue for this in the gtk repo. This is the shell repo. Otherwise you could mean the overview close button? This is pretty much the final design

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/gtk-communitheme/issues/369

**Comment by mivoligo** [comment]
Thanks! Organization of all this is a bit confusing to me ;)
