### ISSUE TITLE
No hover effect for buttons on background windows

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gnome-shell-communitheme#165]
When you have few windows opened and hover your mouse over minimize, maximize buttons of a window in the background, there's no change how those buttons look. You could think clicking them would have no effect.

**Comment by Feichtmeier** [comment]
Yes I agree but there were arguments against it from @madsrh and @clobrano ;0

**Comment by Feichtmeier** [comment]
But this is again the wrong repo. Please look for the orange on close button issue in the gtk repo and post there :)

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/gtk-communitheme/issues/369

**Comment by madsrh** [comment]
I think the discussion is in one of the [backdrop issues](https://github.com/ubuntu/gtk-communitheme/issues?utf8=%E2%9C%93&q=is%3Aissue+backdrop), maybe: https://github.com/ubuntu/gtk-communitheme/issues/194 or hidden in a PR somewhere.

**Comment by madsrh** [comment]
Btw I don't remember having arguments against this since the rework of the backdrop, but I'm unsure which issue this comment was in.

**Comment by ya-d** [comment]
I don't remember any arguments against this either – but many **for** it… 😝
See [gtk#123](https://github.com/ubuntu/gtk-communitheme/issues/123), [gtk#166](https://github.com/ubuntu/gtk-communitheme/pull/166), [gtk#194](https://github.com/ubuntu/gtk-communitheme/issues/194).
