### ISSUE TITLE
Windows previews in the dock need some design love

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gnome-shell-communitheme#167]
I've reported a bug about inconsistency of the previews against Ubuntu dock package before: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1768543
But I believe the previews would benefit from special treatment for this theme.
Currently they look like these:
1. After left click
![preview_l_click](https://user-images.githubusercontent.com/1629120/39654448-c3526036-4fec-11e8-8cd6-931daa7362c0.png)
2. After right click and selecting 'all windows'
![preview_r_click](https://user-images.githubusercontent.com/1629120/39654474-e00061b0-4fec-11e8-81f5-ff87f5c45227.png)

**Comment by Feichtmeier** [comment]
That report was the correct thing to do. 
It's a dash to dock issue. 
We had an issue about this before but I closed it for the same reason!
Thank you very much for bringing it to dash to dock <3

**Comment by Feichtmeier** [comment]
Same problem on materia:
![screenshot from 2018-05-04 23-50-03](https://user-images.githubusercontent.com/15329494/39654624-ea1555bc-4ff5-11e8-9b2f-d73644cde428.png)
![screenshot from 2018-05-04 23-49-50](https://user-images.githubusercontent.com/15329494/39654626-ea46a43c-4ff5-11e8-88bb-062d57672015.png)

It's a dash to dock issue

**Comment by mivoligo** [comment]
OK, got it.
