### ISSUE TITLE
Volume icons chaging on mouse hover 

### ISSUE THREAD

**Issue by patonoide** [ubuntu/gnome-shell-communitheme#169]
I am using the Snap and logged in the communitheme option.

The icon changes when cursor is over it. I am not sure if it's snap related or a bug with gnome.
I did have the ppa installed before using the snap, but I removed gnome-shell-communitheme.

Here is my gnome tweaks 
![tweaks](https://user-images.githubusercontent.com/11774529/39665076-8c22ce16-5064-11e8-9d76-5ccabca2203a.png)

Cursor not over top bar.

![before](https://user-images.githubusercontent.com/11774529/39665097-f15bae88-5064-11e8-922b-ad25ae85fa8f.png)

Cursor over top bar.

![after](https://user-images.githubusercontent.com/11774529/39665106-08998570-5065-11e8-9330-829a19f1a347.png)

**Comment by Feichtmeier** [comment]
Thanks for reporting this. @madsrh you have the snap too, right? Can you confirm this?

**Comment by patonoide** [comment]
It looks like if go into tweaks and change to something and back to Suru it works.

**Comment by patonoide** [comment]
Update: now the same thing is happening for all icons on the top bar. When the cursor is off of it, it resets to the default but when cursor is on the top bar, the icons change to Suru.

**Comment by clobrano** [comment]
I cannot confirm the issue, at least on VM. Witch communitheme version are you using?

`snap info communitheme`

**Comment by madsrh** [comment]
@Feichtmeier I can't reproduce this issue - neither on X or Wayland or running the snap or via PPA.

**Comment by patonoide** [comment]
This is the snap version.

![snapversion](https://user-images.githubusercontent.com/11774529/39674714-82c9fe9e-5126-11e8-9e5d-a65c717c6c5b.png)

I used the Arc-Dark theme for a couple of weeks and did not have this issue. I don't remember this happening with PPA but I can't say for sure since I didn't use it for long.

**Comment by clobrano** [comment]
Something wrong with the installation? Could you try remove the snap and re-install?

**Comment by patonoide** [comment]
Uninstalled the snap, rebooted, installed the snap again, rebooted, logged in the snap, selected communitheme and Suru, rebooted, logged into the snap and the same thing happened with the volume icon...
This is really weird, it affects mostly the same icon. Could it be related to the snap integration?

**Comment by patonoide** [comment]
I could install the Suru pack from the repos.

**Comment by patonoide** [comment]
Using Suru from the repo completely bugs the icons.... Could this be specific to me ?

**Comment by clobrano** [comment]
Some interaction with other themes installed maybe? It's complicated until we find a way to reproduce it

**Comment by patonoide** [comment]
I uninstalled the arc-theme, Volume icon still bugging out.

**Comment by patonoide** [comment]
Fixed it, apparently it has to do with the display manager, I was using lightdm, moved back to gdm and it's not happening anymore.

**Comment by Feichtmeier** [comment]
@patonoide alright thanks for re-checking and don't hesitate to report issues in the future (but please check if they max exist in closed or opened issues)
