### ISSUE TITLE
Titlebar should be a little bit thinner to save vertical screen space

### ISSUE THREAD

**Issue by Tooniis** [ubuntu/gnome-shell-communitheme#179]
Communitheme:
![Communitheme](https://user-images.githubusercontent.com/36982494/39965672-a35ebe3c-56ae-11e8-9a28-1d26ef161183.png)
Ambiance:
![Ambiance](https://user-images.githubusercontent.com/36982494/39965673-a39663d2-56ae-11e8-9461-6fd3c83c07ff.png)

The titlebars in communitheme are quite thick compared to ambiance.
Maybe they should be a little thinner to save vertical screen space.
Maybe this should get reported to upstream GNOME because their adwaita theme has the same titlebars with just a different colour scheme.

**Comment by Feichtmeier** [comment]
Hm, maybe now where we have the circle window controls instead of the squircle the smaller titlebar could work? What's your opinion? :dancer:

**Comment by clobrano** [comment]
Sorry, I was double checking the difference between titlebar and headerbar :smile: 
So, as usual we can try it, no problem for that, however, this will either reduce the clickable area or even the size of window control buttons.

**Comment by clobrano** [comment]
> this will either reduce the clickable area

This is not always evident, but clickable area is not just the circle, it is bigger

**Comment by Feichtmeier** [comment]
Yeah saw this in the other issue. Well then this is either be touch friendly or not? =)

**Comment by clobrano** [comment]
Not just touch friendly, on Ambiance it is not that easy with mouse as well

**Comment by clobrano** [comment]
Closing this here, since it's not the right project
