### ISSUE TITLE
Opaque top bar and dock - separation issues, "grey wall"

### ISSUE THREAD

**Issue by ya-d** [ubuntu/gnome-shell-communitheme#184]
_I opened a new issue to not burry it into a merged pull request (#177). Fell free to close and move elsewhere if needed._

_// edit: Sorry if thats a dupe to #173, I expected this to be closed by #177._

Some apps like Software or Calendar have no left border on their header bar (see [gtk/#447](https://github.com/ubuntu/gtk-communitheme/issues/447)) which also affects separation from the dock when maximized.
<img width="389" alt="maximized - missing border" src="https://user-images.githubusercontent.com/30781876/40162993-e74858ce-59b5-11e8-9eb7-b3934a441a7b.png">

Also this commit reintroduced the issue of a lot of uniform grey on the top/left when windows are maximized. [Jaggers came up with a proposal](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1088) (darker grey for top bar and dock with light border/separation line) which should be worth a try:
![jaggers-proposal maximized](https://user-images.githubusercontent.com/30781876/40162982-e37cd436-59b5-11e8-9eab-f704d754a787.png)

**Comment by clobrano** [comment]
Hi @ya-d thank you for reporting this, we're working on it :+1:

**Comment by Feichtmeier** [comment]
I'd say this is fixed with https://github.com/ubuntu/gnome-shell-communitheme/pull/189
Closing it =)
