### ISSUE TITLE
Black tint on notification emojis

### ISSUE THREAD

**Issue by RBFraphael** [ubuntu/gnome-shell-communitheme#191]
Hi!

For some time, I'm having this issue. If I receive some notification with an emoji (emoticon, smile, whatever), the icon is tinted with a black color.

I've tested this with WhatsApp Web on Chrome and WhatsApp and Facebook Messenger on Franz ( https://meetfranz.com/ ) and this bug stills on these. So, I think is a bug of Communitheme Gnome Shell, not of that softwares. See the prints bellow.

![emoji-black](https://user-images.githubusercontent.com/2997670/40587127-8badbc04-61a1-11e8-9641-c1113505d1cd.png)
![emoji-black-2](https://user-images.githubusercontent.com/2997670/40587128-8bcec03e-61a1-11e8-8b2b-68e872577b77.png)

Sorry for my bad english rsrs

**Comment by Feichtmeier** [comment]
Hi @RBFraphael thanks for reporting issues

Yes I tried several thing to fix this - yet without success. This is also happening in other shell themes which use light notifications like @nana-4 materia or @vinceliuice canta theme. The solution would prbly be to force monochrome emojis instead of colorized ones because the color emojis get colored by the text of the message

**Comment by RBFraphael** [comment]
I don't have knowledge about theming haha But I look the themes are writed with CSS (I think). Emojis on notifications looks using some "background-blend-mode" (or something like this) whichs blend an black color (with alpha). No chance to use an selector (something like ".light-notification i.emoticon" - I'm a bit crazy hahaha) to remove the black tint?

**Comment by Feichtmeier** [comment]
I talked to one of the gnome devs about this, this is unfixable for now. The only fix would be to go back to dark notifications, which would be a bit exaggerated for "only" the emojs. 
@madsrh go back to black or live with this emojis issue?

**Comment by madsrh** [comment]
@clobrano go back to black or live with this emojis issue?

**Comment by clobrano** [comment]
emojis issue is really bad :(, but let's keep white notification for me

**Comment by RBFraphael** [comment]
Hi friends!

Does gnome-shell.css supports "-webkit" properties? I think it's doesn't support, but if it does, maybe using a -webkit-stroke with black color and width sufficient for filling all character (and not emoji characters) maybe can be a solution...

**Comment by Feichtmeier** [comment]
@RBFraphael no, sorry this does not seem to work. Could you open a an issue about that on https://gitlab.gnome.org/groups/GNOME/-/issues ?

**Comment by Feichtmeier** [comment]
![screenshot from 2018-06-30 09-09-13](https://user-images.githubusercontent.com/15329494/42122654-4df3be68-7c45-11e8-99e3-04694dc96751.png)

What we can do for now, is to lighten up the text-color a medium amount, this reduces that effect:

![image](https://user-images.githubusercontent.com/15329494/42122658-603f0668-7c45-11e8-9ba1-e79e001a5969.png)

**Comment by clobrano** [comment]
> I talked to one of the gnome devs about this, this is unfixable for now.

@Feichtmeier is there a bug opened about this, or just they say that it's a limitation?

**Comment by Feichtmeier** [comment]
I don't know if there is a bug opened for this tbh :(
I just ninja texted a gnome dev on telegram :dancer:

**Comment by Feichtmeier** [comment]
> emojis issue is really bad :(, but let's keep white notification for me

Yes indeed. I don't feel like throwing the whole concept of light notifications and dialogues in the rubbish bin only because of the dark emojis is a good idea.
I am closing this now since a solution can only be achieved upstream in gnome shell.
