### ISSUE TITLE
Suggestion: consolidate the GNOME Shell theme and the GTK theme

### ISSUE THREAD

**Issue by snwh** [ubuntu/gnome-shell-communitheme#193]
Not sure if you were aware of this or not, but Shell themes can be integrated with a GTK theme by simply including all assets and CSS of the Shell theme in a `gnome-shell` folder within the main GTK theme folder.

This would save from having to maintain, build and package two separate projects.

**Comment by Feichtmeier** [comment]
Ah didn't know this - but I bet the others knew!

Anyways, I would not do this at the moment because it is quiet good to separate the shell and the gtk theme issue because they tend to overflow us from time to time ;O

**Comment by snwh** [comment]
Oh I do know that feeling, GTK themes tend to be very issue prone (I think my Paper GTK theme had somewhere around 200 before I stopped development because it was overwhelming).

**Comment by Feichtmeier** [comment]
It could be a useful suggestion when we "go live" / hitting 18.10, so I keep that opened.

**Comment by Feichtmeier** [comment]
https://community.ubuntu.com/t/merging-repositories-into-a-single-one/6769/3
It's decided to do so, so closing this
