### ISSUE TITLE
Popup submenu colors and borders

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#195]
@ya-d @ubuntujaggers @madsrh 

I've tried this today in daylight and we really need the border imho.
The initial idea from @ya-d to remove the background color of the "parent-entry" e.g. 
.popup-menu.checked 
Looks very good and less "stripy".
The removal of the borders is sadly only usable in fitting light situations.
So I'd suggest changing it back to have borders, it would look like this:

![borders](https://user-images.githubusercontent.com/15329494/40651015-f99b76b8-6334-11e8-8274-0b1540723adf.gif)

This is what I merged (note to myself, don't merge stuff into master after 0:00 -.-):
![opop12132123](https://user-images.githubusercontent.com/15329494/40651095-2d53ad40-6335-11e8-90b0-74ce762780a0.gif)

Try it yourself when sitting outside or near a window, it's really hard to see that something happened beneath the checked area.

**Comment by madsrh** [comment]
I think you should keep the background color behind "Headphones" like there is in the second image.

**Comment by Feichtmeier** [comment]
I did not change it :thinking:
Must be because the size of the gifs differ

**Comment by ya-d** [comment]
I have the same feeling about the borders and even more so for a darker background of the submenu. I could barely see the differences in the screenshots on my phone under less than ideal lighting conditions.

My ideal solution would remove the upper border of the "parent-entry" like @madsrh mocked up (I have no strong opinion on the background color – both work for me):
![Mockup by madsrh](https://user-images.githubusercontent.com/38893390/40627249-d27e9986-62b5-11e8-8f65-50fe26db80ee.png)

**Comment by Feichtmeier** [comment]
@ya-d 
![yoyo](https://user-images.githubusercontent.com/15329494/40655227-fd9ebfac-6340-11e8-89ab-3f78f198fa7c.gif)

**Comment by ubuntujaggers** [comment]
@Feichtmeier Maybe teeeeeeeeny bit brighter?

![image](https://user-images.githubusercontent.com/38893390/40680732-008f99d2-637f-11e8-9c5f-829279c240d5.png)

N.B. I haven't tried to restore the bright background for the parent item here... "frederik" is only bright because the cursor is hovering, to show that the submenu has enough contrast between the rest of the panel _and_ the highlight for hover.

**Comment by Feichtmeier** [comment]
![lool](https://user-images.githubusercontent.com/15329494/40680980-1703ba0a-6388-11e8-9dcf-51de5b76baf7.gif)
now 7% lighter

**Comment by ubuntujaggers** [comment]
Well I'm happy :)

**Comment by Feichtmeier** [comment]
@madsrh @ya-d happy, too?

**Comment by madsrh** [comment]
@Feichtmeier I know you said flat, but could you **try** just as a test, to make the top border jet or black and post another gif? Then I'll leave it!

IMHO [this ](https://github.com/ubuntu/gnome-shell-communitheme/issues/195#issuecomment-392914533)isn't 100% there yet - it's good and it's better than before indeed.

**Comment by Feichtmeier** [comment]
@madsrh only the top border?

**Comment by Feichtmeier** [comment]
![previews](https://user-images.githubusercontent.com/15329494/40689249-bc7d554a-63a1-11e8-94c2-36ea077716e6.gif)
![blackondark](https://user-images.githubusercontent.com/15329494/40689250-bc98b132-63a1-11e8-9ad2-a178978fffa8.gif)
![blackonwhite](https://user-images.githubusercontent.com/15329494/40689251-bcb46bde-63a1-11e8-8952-d1cdfea9e7b1.gif)

That's with both borders jet

**Comment by Feichtmeier** [comment]
![srsly](https://user-images.githubusercontent.com/15329494/40689608-2fd4059c-63a3-11e8-887a-86814c31e6bd.gif)
Srsly? xD

**Comment by Feichtmeier** [comment]
![genug3](https://user-images.githubusercontent.com/15329494/40710224-5da91e94-63f8-11e8-98aa-6c6152a19eaf.gif)
![genu2](https://user-images.githubusercontent.com/15329494/40710226-5e3b15ba-63f8-11e8-95ab-1ea76777bccd.gif)
![genug](https://user-images.githubusercontent.com/15329494/40710227-5e73e214-63f8-11e8-9d7b-102388f66c3e.gif)

Okay I brightened it up further, I think this is even quiet visible on bright desktops.
@madsrh is this okay?

**Comment by ubuntujaggers** [comment]
I like that @Feichtmeier, these refined shades increasingly make the separators look more natural/less stark to my eye.

**Comment by clobrano** [comment]
> I do still prefer the "3d" solution, but I think I'm alone here

doh! I'm too late

**Comment by Feichtmeier** [comment]
Then we need to adapt the rest of the shell to that. If this is really the design you want than let's make it right and not one part flat and the other part 3d. :thinking: 
So far the shell seems to be that what @luxamman thought of, a soft flat shell that looks like a piece of black silk is dropping off the top of the screen. 
The notifications and dialogue buttons do not fit into this, neither - if it would be only me I'd would adapt that buttons to the pop-ups (except the colour). So I've seen @godlyranchdressing @madsrh and @clobrano all wishing for a shell with 3d pressed effects. So I don't want to be the blocker here. But if we do this please let's do it everywhere and not only in certain parts of the 🐚.
Maybe you should post some mockups on the mock-up thread then and rethinking the shell. I think those questions are better answered in a wider scope. If we only look in those very detailed parts it might be possible to lose the design ideas that were made for the whole 🐚

**Comment by clobrano** [comment]
> Then we need to adapt the rest of the shell to that. If this is really the design you want then let's make it right and not one part flat and the other part 3d. thinking

I see it more like a tape effect (not that I understood the meaning, I can use it :D), in origami style. So it is still flat, but at different levels. This is in line with popups and windows and everything else.

I would't use 3d pressed effect on buttons though, I already like them as they are (except close, settings and lock button that do not have the border, but I can propose a PR for that)

**Comment by Luxamman** [comment]
I also would not prefer a 3D effect here, also because it has no better visibility. the borders here were on my agenda for some time, good to clean that a little up. thanks, guys!

**Comment by ubuntujaggers** [comment]
I'm happy to have a go at mocking up 3D effects/"levels" here for discussion/consideration. I don't object to it in principle. Looking at my previous attempts on my phone, I do see that the darker background didn't work as well as I thought it did on my laptop, however.

What I will say is, I think the current implementation by @Feichtmeier already works, so we can play with mockups at leisure and only change the shell if we get a popular alternative. You've already got something good IMO so that is a strong position to experiment from.

**Comment by madsrh** [comment]
I don't have time to write a propper reply amt. Can we stop posting here and move this to [the hub](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/297).

A quick note: I don't think of this as 3d (_origami style sounds good_) and I don't think it will break the user experience. We have lots of 3d stuff in the GTK theme - does the user know the difference between shell and GTK? 
I agree that it isn't a perfect solution to add this, but IMHO it makes the UI **so much more** logic/obvious what's going on, and I would rather have that. If we can find a flat design that makes sense, I would be perfectly happy with that too. 

Let's continue this in on the hub 😃

**Comment by Feichtmeier** [comment]
[  ok :D  ](    https://community.ubuntu.com/t/mockups-new-design-discussions/1898/299?u=frederik-f )
