### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#197]
With the recent transparency increase the messages look a bit too much like a "transplantation" onto the message tray, because they are 100% opaque and the background is quiet transparent:

![screenshot from 2018-05-30 18-27-46](https://user-images.githubusercontent.com/15329494/40733921-2e41ba82-6437-11e8-9948-41c9252ce911.png)

First ideas:

A) Make them as transparent as the tray:
![screenshot from 2018-05-30 18-28-38](https://user-images.githubusercontent.com/15329494/40733958-4b9d6860-6437-11e8-9e3d-49310302ac99.png)

B) 70% transparency of the message upon the tray:
![screenshot from 2018-05-30 18-29-51](https://user-images.githubusercontent.com/15329494/40734028-8b9c4a76-6437-11e8-94f2-67cbf4845d08.png)

Any further ideas @madsrh @luxamman @ubuntujaggers @clobrano @ya-d or anyone else?

**Comment by mivoligo** [comment]
My vote for the option A

**Comment by madsrh** [comment]
**B**

**Comment by Luxamman** [comment]
B
