### ISSUE TITLE
python 3.6 GTK Warning

### ISSUE THREAD

**Issue by naquiroz** [ubuntu/gnome-shell-communitheme#198]
Just to let you guys know, I'm getting a deprecated warning while using the theme, programming in python, with PyQt5. The warring is as follows.

`(python3.6:7260): Gtk-WARNING **: 16:11:56.781: Theme parsing error: gtk.css:2675:51: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

**Comment by Feichtmeier** [comment]
Thanks for reporting @naquiroz !
@chrisjbillington has reported the same issue on the gtk repo. I am not sure if the shell theme or the gtk theme causes this, we use :insensitive in both the shell and the gtk theme scss files. :thinking:
