### ISSUE TITLE
snap installation difference?

### ISSUE THREAD

**Issue by naquiroz** [ubuntu/gnome-shell-communitheme#202]
How can i see if I installed the gnome-shell theme or the gtk version?  All i did was install by snap.

**Comment by Feichtmeier** [comment]
@naquiroz you installed both when you installed the snap. Gtk theme is for GNOME applications, shell theme is for the GNOME shell. 
Please don't use issues to ask questions... we have more than enough opened. 
Best regards :smiley_cat:
