### ISSUE TITLE
Ubuntu AppIndicators wrong behaviour

### ISSUE THREAD

**Issue by RBFraphael** [ubuntu/gnome-shell-communitheme#203]
Hi! I've re-installed my Ubuntu 18.04 and Communitheme (snap). After that, I noticed a bug (which was present before, but I had not noticed) in Gnome Shell.

On Ubuntu default session, AppIndicators works normal, showing all my icons.
![ubuntu-normal](https://user-images.githubusercontent.com/2997670/40881286-005140c0-6699-11e8-9434-4f490ab24892.png)

But, on Communitheme Snap session, some icons (in my case, Skype and Franz) are not showing.
![communitheme-normal](https://user-images.githubusercontent.com/2997670/40881289-1b9d3e92-6699-11e8-8bed-4244a70119f4.png)

And, curiously, after some time with my computer locked, after unlocking all icons have disappeared!
![communitheme-bug](https://user-images.githubusercontent.com/2997670/40881293-3d77828e-6699-11e8-84ff-2b51f76716a9.png)

After searching a bit on internet, I found this article https://github.com/ubuntu/gnome-shell-communitheme/issues/95 and tried to add `XDG_CURRENT_DESKTOP=Unity` to my `/etc/environment` file, but nothing changes.

Thank you :smile: and sorry for my english haha :rofl:

**Comment by clobrano** [comment]
Hi @RBFraphael, thanks for helping us. This is a bug we already reportede upstream, since communitheme can. I nothing about it
