### ISSUE TITLE
Orange border status menu and notifications

### ISSUE THREAD

**Issue by Luxamman** [ubuntu/gnome-shell-communitheme#208]
There was already a discussion about the status menu, but I have to ask if we tried to match the selection in the status menu like it is in notifications/calendar:

![orangeborder](https://user-images.githubusercontent.com/20417555/41180153-95e8f334-6b6d-11e8-9737-46df4c858174.png)
Here we have the orange border.

![noorange](https://user-images.githubusercontent.com/20417555/41180171-a2432db6-6b6d-11e8-87ad-3cae5e88db13.png)

And what about trying to match the selection like the calendar view in the notifications? Maybe it is possible to have an orange border and looks good, also having the lighter background only on hover. The status menu still looks little out of place to me, maybe because following different design rules.

**Comment by Feichtmeier** [comment]
This status menu popup uses the same styling as all other popups for that submenu. So if we would use an orange selection it would also be applied here:
![screenshot from 2018-06-08 22-55-42](https://user-images.githubusercontent.com/15329494/41180626-18733a70-6b6f-11e8-8d7f-0dec5c25e38e.png)
And here:
![screenshot from 2018-06-08 22-56-21](https://user-images.githubusercontent.com/15329494/41180669-306540ec-6b6f-11e8-98ba-5cedb50a53ee.png)

**Comment by Feichtmeier** [comment]
![screenshot from 2018-06-09 00-27-01](https://user-images.githubusercontent.com/15329494/41183609-e95d3e9a-6b7b-11e8-8ca3-12aa8985e6d5.png)
![screenshot from 2018-06-09 00-26-53](https://user-images.githubusercontent.com/15329494/41183610-e983644e-6b7b-11e8-8dcf-3fa4fdacb8c8.png)
![screenshot from 2018-06-09 00-26-43](https://user-images.githubusercontent.com/15329494/41183611-e9a40852-6b7b-11e8-97bf-2f92a84dbb53.png)

That's the same inset box-shadow but orange :thinking: 
Was that what you meant?

**Comment by Luxamman** [comment]
Is left/right border possible and no lighter background?

**Comment by clobrano** [comment]
I am not sure about this change. We usually don't have orange in selected menus

**Comment by Feichtmeier** [comment]
@Luxamman  like this?
![screenshot from 2018-06-09 13-55-59](https://user-images.githubusercontent.com/15329494/41191247-dcb40f54-6bec-11e8-8ca6-b26c46cfd518.png)
![screenshot from 2018-06-09 13-55-46](https://user-images.githubusercontent.com/15329494/41191248-dcced834-6bec-11e8-98fa-859483318ede.png)
![screenshot from 2018-06-09 13-55-34](https://user-images.githubusercontent.com/15329494/41191249-dce6af36-6bec-11e8-83fc-7e709dc9f63a.png)

I'd prefer the current version. Which is on par with:

![image](https://user-images.githubusercontent.com/15329494/41191255-f11c8c0a-6bec-11e8-804d-296631c3e453.png)
and
![image](https://user-images.githubusercontent.com/15329494/41191289-9643381e-6bed-11e8-91df-4a95be1004d8.png)

**Comment by Luxamman** [comment]
Was worth a try :)
Thanks!
