### ISSUE TITLE
Installing GDM Theme on non-Ubuntu System

### ISSUE THREAD

**Issue by Miridyan** [ubuntu/gnome-shell-communitheme#209]
Not so much and issue, and more of a question about installing the Communitheme GDM theme. I don't use ubuntu and the instructions for installing communitheme and whatnot require Snapcraft, which a lot of other distros just dont' have. Would it be possible to get install instructions for installing the gdm theme for non-snapcraft/non-ubuntu systems?

**Comment by clobrano** [comment]
Hi @Miridyan, sorry for the late reply. Which distro do you use?

**Comment by Miridyan** [comment]
I use Arch Linux

**Comment by clobrano** [comment]
In general, you should be able to install from source, which is explained in https://github.com/ubuntu/gnome-shell-communitheme/blob/master/CONTRIBUTING.md

**Comment by Miridyan** [comment]
Unfortunately, the instructions for setting the gdm theme require update-alternatives, which is a debian-based exclusive command.

**Comment by clobrano** [comment]
Pity, but I guess there's some kind of Arch alternative

**Comment by Miridyan** [comment]
ah, i figured it out. Basically i needed to create a gresrouce xml file and compile my own version of `gnome-shell-theme.gresrouce` and put it in `/usr/share/gnome-shell`. In case anyone is wants to use it, this is the file I wrote.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
    <gresource prefix="/org/gnome/shell/theme">
        <file>calendar-arrow-left.svg</file>
        <file>calendar-arrow-right.svg</file>
        <file>calendar-today.svg</file>
        <file>checkbox-focused.svg</file>
        <file>checkbox-off-focused.svg</file>
        <file>checkbox-off.svg</file>
        <file>close.svg</file>
        <file>close-window-active.svg</file>
        <file>close-window-hover.svg</file>
        <file>close-window.svg</file>
        <file>corner-ripple-ltr.svg</file>
        <file>corner-ripple-rtl.svg</file>
        <file>dash-placeholder.svg</file>
        <file>dots.svg</file>
        <file>filter-selected-ltr.svg</file>
        <file>filter-selected-rtl.svg</file>
        <file>gnome-shell.css</file>
        <file>gnome-shell-high-contrast.css</file>
        <file>lockscreen-gradient.svg</file>
        <file>logged-in-indicator.svg</file>
        <file>message-indicator-symbolic.svg</file>
        <file>modes/ubuntu-communitheme.json</file>
        <file>no-events.svg</file>
        <file>noise-texture.png</file>
        <file>no-notifications.svg</file>
        <file>pad-osd.css</file>
        <file>page-indicator-active.svg</file>
        <file>page-indicator-checked.svg</file>
        <file>page-indicator-hover.svg</file>
        <file>page-indicator-inactive.svg</file>
        <file>process-working.svg</file>
        <file>running-indicator.svg</file>
        <file>source-button-border.svg</file>
        <file>summary-counter.svg</file>
        <file>toggle-off-hc.svg</file>
        <file>toggle-off-intl.svg</file>
        <file>toggle-off-us.svg</file>
        <file>toggle-on-hc.svg</file>
        <file>toggle-on-intl.svg</file>
        <file>toggle-on-us.svg</file>
        <file>ubuntu-logo-icon.svg</file>
        <file>ws-switch-arrow-down.svg</file>
        <file>ws-switch-arrow-up.svg</file>
    </gresource>
</gresources>
```

Just `sudo cp /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.backup` and then `sudo glib-compile-resources --target=/usr/share/gnome-shell/gnome-shell-theme.gresource communitheme-shell.gresource.xml` then reboot your computer. _Always_ backup the original gresource file because if something messes up, GDM won't start.

**Comment by Miridyan** [comment]
Everything you'll need to get this file to work is in `/usr/share/themes/Communitheme/gnome-shell`. Just copy everything into an empty directory and save this XML file in there as well. Then just follow the commands above.

**Comment by Feichtmeier** [comment]
nice!
@didrocks can we use this for our GDM problems? (Wrong user icon, wrong panel indicator icons)

**Comment by didrocks** [comment]
No, we shouldn't create a gressources replacing default data set. That will erase as well default upstream theme. It's not a distro-wide solution.

Hum, the wrong user icon and panel indicator are due to another issue (not the good default theme set for gdm user), something to open a bug for or remind me when we switch to it :p
