### ISSUE TITLE
In the emoji picker, the searchbox is misaligned

### ISSUE THREAD

**Issue by jlemonde** [ubuntu/gnome-shell-communitheme#211]
Upper border is too large, or side borders too thin.

![capture d ecran de 2018-06-11 08-57-38](https://user-images.githubusercontent.com/30623792/41216774-03af167a-6d56-11e8-9462-8dc5c477e4c2.png)

**Comment by Feichtmeier** [comment]
Been fixed some days ago by Vince. Should be in stable snap soon

**Comment by Feichtmeier** [comment]
And this is the wrong repo. That's a gtk issue not gnome shell.
Here is the fix: https://github.com/ubuntu/gtk-communitheme/pull/529
