### ISSUE TITLE
Did not display the skype indicator in the top bar of ubuntu

### ISSUE THREAD

**Issue by hudsonbrendon** [ubuntu/gnome-shell-communitheme#212]
I noticed that the skype indicator is not displayed on the top bar, slack was not appearing but recently it is appearing, could someone solve this?

**Comment by clobrano** [comment]
Hi @hudsonbrendon thanks for taking time to report this. However, please have a look at the already opened tickets. This one as been reported [here](https://github.com/ubuntu/gnome-shell-communitheme/issues/95) and does not depend on us.
