### ISSUE TITLE
recent update gives files/nautilus white bg color. text unreadable with global dark theme.

### ISSUE THREAD

**Issue by iambumblehead** [ubuntu/gnome-shell-communitheme#213]
I've been enjoying communitheme with global dark theme enabled.

_~/.config/gtk-3.0/settings.ini_
```
[Settings]
gtk-application-prefer-dark-theme=1
```

Things have been great but today nautilus began using a white background color where previously the background had been dark. screenshot included:

![nautilus-white-bg](https://user-images.githubusercontent.com/2058705/41328788-e0c73bea-6e7e-11e8-8e0c-0f5ac835826c.png)

**Comment by clobrano** [comment]
Hi @iambumblehead, I didn't know about `~/.config/gtk-3.0/settings.ini`, this will help us a lot testing dark theme, thanks a lot!

So far, a complete dark theme was not the main target of Communitheme, we could only fix what was visible through applications that use the dark theme by default (e.g. Gnome Video, Gnome Photos) or by selecting a flag in the application itself (Gnome Todo).
