### ISSUE TITLE
Cannot open folders or links (shortcuts) in the desktop 

### ISSUE THREAD

**Issue by rypz79** [ubuntu/gnome-shell-communitheme#217]
[https://askubuntu.com/questions/1047275/no-folders-or-links-on-desktop-in-communitheme](https://askubuntu.com/questions/1047275/no-folders-or-links-on-desktop-in-communitheme)

**Comment by clobrano** [comment]
Hi @rypz79, as initially discussed on Askubuntu, starting from version 3.28 Nautilus dropped support for desktop icons

https://www.omgubuntu.co.uk/2018/01/gnome-desktop-icons-removed-3-28

communitheme has no power on this, so I guess that it is just a coincidence that you installed the theme and then discovered this issue
