### ISSUE TITLE
[Nemo integration] Places sidebar - place disappear at click

### ISSUE THREAD

**Issue by rypz79** [ubuntu/gnome-shell-communitheme#227]
Redirected from [https://github.com/linuxmint/nemo/issues/1884](url)

![screenshot from 2018-06-30 20-51-09](https://user-images.githubusercontent.com/28814757/42134110-796fee74-7d3d-11e8-8116-407bf6a85c80.png)

![screenshot from 2018-06-30 20-51-19](https://user-images.githubusercontent.com/28814757/42134112-8e5fa55e-7d3d-11e8-8973-d385d5214776.png)

Nemo works fine with all my other themes

**Comment by Feichtmeier** [comment]
Hi thanks for reporting issues. This is sadly the wrong repo :(
Use this one:
https://github.com/ubuntu/gtk-communitheme

On a sidenote: we don't officially support linux mint apps. This theme is made for GNOME. But maybe one of us finds time for this - yet no promise.
