### ISSUE TITLE
Suggestion: Reduce the size of the top panels

### ISSUE THREAD

**Issue by izznogooood** [ubuntu/gnome-shell-communitheme#228]
Are you considering this? It looks strange with the default font size and takes opp screen space.

![screenshot from 2018-07-01 15-42-11](https://user-images.githubusercontent.com/23040578/42135016-8d0bcb1c-7d45-11e8-96c1-373a9d2fd817.png)

Unless your targeting touch screens...

**Comment by Feichtmeier** [comment]
Hi thanks for reporting issues!
This is sadly the wrong repo :(
Use this one: https://github.com/ubuntu/gtk-communitheme
