### ISSUE TITLE
Gtk warning typora

### ISSUE THREAD

**Issue by naquiroz** [ubuntu/gnome-shell-communitheme#229]
Hi! I'm not sure if it is a bug from communitheme or typora, but I'm getting this warning when using typora (markdown editor) for ubuntu.
```
 (typora:12647): Gtk-WARNING **: 00:33:56.298: Theme parsing error: gtk.css:2136:20: Junk at end of value for color
```
If the warning is not communitheme-relate, I will happily close it.

**Comment by clobrano** [comment]
Hi Nicolás, thank you for reporting this. It is related to communitheme,
but it has reported already and a fix is ready ;)

Il lun 2 lug 2018, 06:42 Nicolás Quiroz <notifications@github.com> ha
scritto:
