### ISSUE TITLE
Update app launcher icon

### ISSUE THREAD

**Issue by godlyranchdressing** [Ubuntu/gnome-shell-communitheme#23]
Discussion thread: https://community.ubuntu.com/t/mockups-new-design-discussions/1898/162

Mockups that no consensus has been reached on:

![34910897-694e3838-f8be-11e7-98e9-a06e380da737](https://user-images.githubusercontent.com/27529229/35154369-6b5767f8-fd00-11e7-96ca-eefe2b169684.png)
![34906944-1d2216ce-f877-11e7-9725-9ceff59d9114](https://user-images.githubusercontent.com/27529229/35154370-6b78c362-fd00-11e7-8b68-65e36eefb6ca.png)

Overall, the icon needs to be smaller to be [closer to Unity 8's](https://www.howtoforge.com/images/how-to-test-mir-and-unity-8-on-ubuntu-16-04/big/pic_7.png).

**Comment by goede** [comment]
Maybe something to keep in mind; the icon in the new theme does not meet the official brand guidelines.

![ubuntu-logo51](https://user-images.githubusercontent.com/7457885/35917862-fbd1b8ec-0c0f-11e8-86dc-639bc543927b.png)

https://design.ubuntu.com/brand/ubuntu-logo/

**Comment by NusiNusi** [comment]
white or black!
Another idea: change the black of the black-version into the same color gnome-shell uses when your open a menu of gnome-shell (at the moment it is a very dark grey). So it would look more like the icon belongs to the system and is not an own app.

**Comment by clobrano** [comment]
Current logo looks like the latter without the black circle, is this the problem?

**Comment by clobrano** [comment]
closed by #67
