### ISSUE TITLE
Update GDM gradient to be closer to mockup

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gnome-shell-communitheme#24]
As far as I know, this can't be 1:1 and I'm not sure how to go about making it look like an exact match of the mockup. Right now the gradient effect is created by having a solid purple background and having a semi-transparent white gradient on top of it (lockscreen-gradient.svg) to give it the illusion of a purple gradient. 

In this mockup it's #15030f -> #472c3f

![34853142-8c5ac6c6-f732-11e7-801f-2a1a6315b02f](https://user-images.githubusercontent.com/27529229/35154505-d443907a-fd00-11e7-892e-d31cd64cd75a.jpg)

I think the most we can do is make the colors darker as they're much lighter right now.

**Comment by madsrh** [comment]
Nice job 👍
Although it's not in this mockup by @luxamman, I think we should use the Suru style user icon.
![image](https://user-images.githubusercontent.com/3986894/35155300-7da705c6-fd2d-11e7-9f59-43188277c819.png)

https://github.com/CanonicalLtd/desktop-design/blob/master/User%20icon/user-icon.svg

**Comment by clobrano** [comment]
> Question: did you try with multiple monitors having different resolutions?
I tried with my 13'' screen 1920x1080 and it works nicely. Only the "login" button is purple instead of green. Should I open a bug for that?

**Comment by didrocks** [comment]
@clobrano sorry for not being clear enough, what I actually meant was "testing in a multi-monitor configuration, when the 2 monitors don't have the same resolution".

**Comment by clobrano** [comment]
@didrocks ah ok 😄 
What about the login button? Is it purple for me only?

**Comment by Feichtmeier** [comment]
@godlyranchdressing isn't this already fixed?

**Comment by Feichtmeier** [comment]
@clobrano @godlyranchdressing 
Fixed the login button to be green:
![image](https://user-images.githubusercontent.com/15329494/39773270-d4aec6ae-52f7-11e8-9293-9173e2bf0049.png) will commit this into the next shell PR

So what's missing?

**Comment by clobrano** [comment]
The default icon should be circular instead that like a squircle

**Comment by Feichtmeier** [comment]
I've talked a bit to @3v1n0 and it seems like the wrong icons in the top panel and popups and the default-user-icon problems could be rather related to some env variable rather than a correct url("....") path.

**Comment by Feichtmeier** [comment]
Closing this as this is migrated as an issue to the gtk repo: https://github.com/ubuntu/gtk-communitheme/issues/583

**Comment by taciturasa** [comment]
For a project that's in general incredibly bright and colorful, this seems surprisingly muted and drab of a gradient choice. I feel like maybe the colors need to be lighter and a bit more saturated?

**Comment by madsrh** [comment]
I agree @taciturasa 😃 

> ...which will be the very first window into the system...

Although, one might argue that the boot screen is 'muted and drab' too 😉 

Do you have a suggestion? 

We had other ideas in [this thread ](https://community.ubuntu.com/t/design-mockups-updates-designer-only/2053)_(just search for GDM)_

**Comment by taciturasa** [comment]
Again, I'm still not sure of our other technical limitations, but my further reading does provide me info that GTK/Shell CSS both support animations, which I'm sure you guys probably already knew, I'm just new and slow 😊

With that being said, and with some previous experimentation with minor shell tweaks, it seems like it would be possible to form the background color of the GDM screen as the same exact solid shade of purple ended up in use (with this idea) on the plymouth screen as the GDM background-color, and then apply an animation to the background-color to transition between the purple and the purple-orange gradient. I'll put together a fiddle later messing around with this idea, but these are my current thoughts.

**Comment by clobrano** [comment]
> Was there a reason this wasn't what you went with?

I guess the reason is that none of us is skilled with svg tools :D

> my further reading does provide me info that GTK/Shell CSS both support animations

Not sure you're talking about the Login page though, which is slightly different. You found evidence of animation for this page?

> I'll put together a fiddle later messing around with this idea, but these are my current thoughts.

Looking forward to this :) hopefully with css tricks available on gdm login
