### ISSUE TITLE
Missalignment between the newly appeared Ubuntu icon and the close button if on the left side.

### ISSUE THREAD

**Issue by jlemonde** [ubuntu/gnome-shell-communitheme#242]
For those who like to have the close button on the left side, the issue is, when the window is in full screen, that the Ubuntu icon, which is newly appeared within the activities button, is not aligned with the close button. Is it possible to reduce the margin all around the Ubuntu icon ??

![capture d ecran de 2018-07-14 09-32-15](https://user-images.githubusercontent.com/30623792/42722235-f7e987aa-8748-11e8-99de-2723537f39a1.png)

**Comment by Feichtmeier** [comment]
Yes it's possible. :)
I keep this opened. We need a good solution for all situations. Settings tweaked from default are ofc a little bit less priority than default settings but this is an easy change

**Comment by Feichtmeier** [comment]
Ah But please open the issue on the gtk repo we move the code there soon
