### ISSUE TITLE
Text cursor not visible in Nautilus location bar

### ISSUE THREAD

**Issue by slackmate** [Ubuntu/gnome-shell-communitheme#33]
In Nautilus when I press `CTRL + L` to enter the path manually in the location bar the text cursor is almost invisible against the dark background. This is on Ubuntu 17.10.1

Version: 18.04\~wip1+201801240731+097b554\~ubuntu17.10.1

**Comment by clobrano** [comment]
Hi, thanks for reporting this 🥇 

This is actually a gtk3 theme issue, not a gnome-shell one, but I am going to move this to the right repository.

**Comment by slackmate** [comment]
@clobrano Thanks for moving the issue to the right repository :thumbsup:
