### ISSUE TITLE
Overview search entry field is too tall, login screen entry field should be semi-transparent

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gnome-shell-communitheme#38]
The search field in the overview is a little too tall due to the increase in height (that fixes the login entry field gaining height when text is entered). 

The text entry field on the login screen would look a little bit better than it does now with a semi-transparent background (white or black).

**Comment by Feichtmeier** [comment]
@godlyranchdressing what do you think of giving the search field a little bit of transparency when you fix this issue?
Some things changed since you opened it: every other element has transperency now in the shell overview :) The black search entry could use some, too imho

**Comment by godlyranchdressing** [comment]
I've fixed the height issue in #109 but I didn't bother with the transparency because it didn't help the lockscreen's entry field look less awkward. I think it look a little clunky against the purple background.

@Feichtmeier The overview search field? I think that'll only be visible if the entry field were white, it's dark now and I tried with transparentize($c, 0.15) and you really can't tell.

**Comment by Feichtmeier** [comment]
@godlyranchdressing @clobrano  what do you say? If you +1 I'll do that if you tell me where you defined the dock and panel transparency
Let's use the same transparency for all stuff in gnome dash:
![screenshot from 2018-04-30 19-32-03](https://user-images.githubusercontent.com/15329494/39441273-aa9666ba-4cad-11e8-9093-1ea54213e645.png)

**Comment by Feichtmeier** [comment]
@godlyranchdressing I fixed the transparency after talking to mads.

I still fail to see how the search field is too big?
![screenshot from 2018-05-01 09-32-30](https://user-images.githubusercontent.com/15329494/39465251-9ec3cd58-4d22-11e8-8db3-416a5c523429.png)

=) Compared to adwaita?

**Comment by Feichtmeier** [comment]
Closing this as the transparency issue is fixed and you fixed the height
