### ISSUE TITLE
In Save Window, the File Name entry box: cursor has become invisible against black background (Communitheme)

### ISSUE THREAD

**Issue by Astrowatt** [Ubuntu/gnome-shell-communitheme#39]
See picture: Due to a recent change in the Communitheme colours in the File Name entry box when saving files, the cursor is now invisible. (Black against black? ...)
![schermafdruk van 2018-01-29 09-25-08](https://user-images.githubusercontent.com/29024246/35500597-47ceb668-04d7-11e8-91d0-4bb9100a0629.png)

**Comment by clobrano** [comment]
Not sure with which commit, but this one looks fixed now. @Astrowatt could you confirm this?

**Comment by Astrowatt** [comment]
Hereby confirmed! Posh white vertical cursor! :+1:
