### ISSUE TITLE
Install theme on /usr/share/themes

### ISSUE THREAD

**Issue by irondave** [Ubuntu/gnome-shell-communitheme#41]
Right now if you install gnome-shell-communitheme from ppa, with apt, the installed theme is stored into /usr/share/gnome-shell/theme but this setup makes the theme undetectable by gnome tweak tool.
My suggestion is to install the gnome-shell theme into /usr/share/themes alongside the gtk2 and gtk3 themes making easier to change themes with gnome tweak tool.

**Comment by didrocks** [comment]
The shell themes are supposed in GNOME Shell code to under in /usr/share/gnome-shell, similarly to the extension place. I suggest you raise a bug in Tweaks to take that directory into account for Shell theme switching.
