### ISSUE TITLE
Match top bar colour with the window title bar one

### ISSUE THREAD

**Issue by irondave** [Ubuntu/gnome-shell-communitheme#45]
My suggestion is to use the same colour for the window title bar and the gnome shell top bar to have the sense of cohesion between themes (gtk and shell).
Alternatively I think it's better to have a darker color shade for the shell instead of the gtk theme or use a lighter color for gtk.

**Comment by clobrano** [comment]
Hi @irondave, thanks for taking time to report this. Currently gnome shell top panel's color and headerbar's one should be the same. Did you see a different one in your installation?

**Comment by irondave** [comment]
I just found a new session into gdm called "ubuntu communitheme" however this is how the theme looks like on "ubuntu communitheme" session:
![ubuntu communitheme](https://user-images.githubusercontent.com/8292014/35748405-3c4cbfb8-084e-11e8-80df-4b092346b67a.png)
you can see a line between the top bar and the window title bar
and here the theme on normal "ubuntu" session:
![ubuntu communitheme](https://user-images.githubusercontent.com/8292014/35748462-67129984-084e-11e8-906c-2fe58b721f8c.png)
as you can see the top bar has another colour

**Comment by clobrano** [comment]
That's right. Communitheme session is the one we are developing and the line is intended to keep the distinction between the two widgets.
You can follow and contribute, if you like, to the discussion on this new theme also [here](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/)
