### ISSUE TITLE
Step under activities on top bar 

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gnome-shell-communitheme#50]
reported first [here](https://github.com/Ubuntu/gtk-communitheme/issues/144)

**Comment by jasonflindt** [comment]
The step under the Activities text is created by the border or line at the top of the Ubuntu-dock

**Comment by jasonflindt** [comment]
The step under the Activities text is created by the border or line at the top of the Ubuntu-dock

**Comment by clobrano** [comment]
Hi @jasonflindt, is this bug still present with the new update?

**Comment by clobrano** [comment]
Closing this now, but feel free to re-open it if you can reproduce it again
