### ISSUE TITLE
 gnome-shell-menu color does not fit the dark color of gtk-theme

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#55]
The gnome-shell-menus (when you click on the time or the volume) has a different dark-grey than the gtk-theme. For consistency it should be the same color. So more brownish or it should have the brighter gray of the gtk-theme. At least the colour of the gnome-shell-menus should be found in the gtk-theme too.
![gnomeshellcolor](https://user-images.githubusercontent.com/36449926/36160391-54ff5444-10e1-11e8-8c66-b8756ffbcbbe.jpg)

It is possible that on some screens you can not see the difference.

**Comment by madsrh** [comment]
+1 I agree that it sends a confusing message. In your screenshot the Nautilus window is in backdrop (unfocused), but I see no reason why the shell shouldn't match the headerbar. @clobrano @godlyranchdressing ?

![color_matching](https://user-images.githubusercontent.com/3986894/36336539-e14fbd90-1388-11e8-9cd7-88812c6fb47c.gif)

**Comment by NusiNusi** [comment]
Glad, i could somehow help. Is a version with a shell that uses the brighter grey colors? At least for the menus. Just for testing?

**Comment by clobrano** [comment]
@Feichtmeier why did you reopen this changing the name?

**Comment by Feichtmeier** [comment]
Sorry I was a bit slow since my gimp skills are freaking bad:

I think the contrast of the dark menues on the dark header bars is quiet low:

![current](https://user-images.githubusercontent.com/15329494/38327665-14a5f1a2-3849-11e8-8bfa-115a3ac7588b.png)

How about rgb(48,48,48):

![rgpb_48_48_48](https://user-images.githubusercontent.com/15329494/38327701-247243c4-3849-11e8-8501-f6aa0b3ca65b.png)

**Comment by NusiNusi** [comment]
White popup menus in the same style like your appnotifications could look nice. but a mockup would only show that.

**Comment by Feichtmeier** [comment]
The white would be anywhere then: OSD (volume popup etc), menus of the top panel, menus of the dock, shell dialogs. This is too much and too shiny I think, though I love the white popup menues of the GTK apps myself

**Comment by clobrano** [comment]
We can discuss that of course, but originally the ticket intended exactly the opposite

> The gnome-shell-menus (when you click on the time or the volume) has a different dark-grey than the gtk-theme. For consistency it should be the same color. So more brownish or it should have the brighter gray of the gtk-theme.

**Comment by clobrano** [comment]
That's right. However I'd prefer open a new ticket about this and revert this to the original meaning

**Comment by NusiNusi** [comment]
@Feichtmeier today i updated the theme and i really love what you did to the gnome-shell-activities and especially the white appnotification. I printed a text and was really happy about how good and professional it looked when i got the notification. Great work! As @clobrano  said you should maybe open a new ticket for a discussion about what could be made about gnome-shell-popup-menus. I would like to see some mockups and ideas in white. thanks for the great work!

**Comment by Feichtmeier** [comment]
@clobrano allrighty. sorry for the confusion caused =D
