### ISSUE TITLE
Suru Icon for Evolution is blue, unfinished squircle

### ISSUE THREAD

**Issue by Astrowatt** [Ubuntu/gnome-shell-communitheme#6]
This is an issue that has been popping up ever since Ubuntu 17.10 was released.

The icon **evolution.png**, in all of the folders 48x48 and downward is the wrong icon. It is just a blue squircle, without the nice image of the letter in it. (See picture.)

The same goes for the files **org.gnome.Evolution.png**, **internet-mail.png** and **mail-app.png**.

It's probably just something that has been looked over, but still: important enought to solve.
![schermafdruk van 2018-01-07 22-21-52](https://user-images.githubusercontent.com/29024246/34654302-29f07f3e-f3fa-11e7-8ed4-0302322fad24.png)

**Comment by galgalesh** [comment]
Thanks! I reported it upstream: https://github.com/snwh/suru-icon-theme/issues/25

The icon theme is currently in pre-alpha state so you'll find more issues with it, but it's good to keep track of what is missing.

**Comment by galgalesh** [comment]
Closing this issue in favor of the upstream bug report.
