### ISSUE TITLE
Atom's menus are barely visible

### ISSUE THREAD

**Issue by Huluti** [Ubuntu/gnome-shell-communitheme#62]
I don't know if you know this problem...

![capture du 2018-02-25 12-23-50](https://user-images.githubusercontent.com/5782198/36640856-15191c26-1a27-11e8-80ec-3a2241ac9ee3.png)

**Comment by clobrano** [comment]
Yes https://github.com/Ubuntu/gtk-communitheme/issues/148
but thank you for taking time to report it! :wink:

**Comment by Huluti** [comment]
Fixed with the last update. Thank's ;)
