### ISSUE TITLE
GDM session names should match Ubuntu's

### ISSUE THREAD

**Issue by fthx** [ubuntu/gnome-shell-communitheme#63]
Hi,

IMHO we should change Communitheme's session names to match Ubuntu's session names. I mean **(nothing) = Xorg** and **Wayland = Wayland**. I found the current names a little bit confusing since Ubuntu's decision to default to Xorg.

**Comment by Feichtmeier** [comment]
This one is fixed in the new snap version of this theme, so I close this now :) Thanks for reporting this
