### ISSUE TITLE
"Add new local clocks" in date topbar menu is too big

### ISSUE THREAD

**Issue by fthx** [ubuntu/gnome-shell-communitheme#64]
Hi,

In the date menu of the topbar (calendar, notif.), the "Add new local clocks" label's font is too large. Maybe a matter of taste but anymway it's larger than default GNOME's theme. I suggest we reduce this font size to normal size (as notifications, e.g.).

**Comment by Feichtmeier** [comment]
@madsrh do you agree? I'd fix it then

**Comment by Feichtmeier** [comment]
@madsrh like this?
![screenshot from 2018-04-30 17-12-42](https://user-images.githubusercontent.com/15329494/39434743-bc5d1d94-4c99-11e8-89b1-96391607bf1a.png)
![screenshot from 2018-04-30 17-12-37](https://user-images.githubusercontent.com/15329494/39434745-bc81cbda-4c99-11e8-95f2-21c7306d87d9.png)

**Comment by madsrh** [comment]
Sorry I forgot about this one 😞 

I'm on my phone atm, but it looks good. I'm not sure if the font should be just a tiny bit smaller or if it's because it's white? 🤔
