### ISSUE TITLE
GNOME's app dock border is not the same as the desktops dock's one

### ISSUE THREAD

**Issue by fthx** [Ubuntu/gnome-shell-communitheme#65]
Hi,

I do not use Ubuntu dock, so the apps dock is GNOME's.
Well, apps dock's border is black but the desktop dock's one is gray. I do not feel that consistent but I don't know if it's intended or not.

Additionally, I don't think that the two docks background colors are the same, the apps dock's one seems to be lighter than desktop dock's one. Maybe my eyes are the issue here, I'm not sure of that. :-)

**Comment by clobrano** [comment]
> Additionally, I don't think that the two docks background colors are the same, the apps dock's one seems to be lighter than desktop dock's one

confirm that, it's by design (@Luxamman)

**Comment by fthx** [comment]
![capture d ecran de 2018-02-26 17-36-22](https://user-images.githubusercontent.com/23138504/36682548-a9f88166-1b1b-11e8-9c3a-c7425cd6e629.png)

**Comment by clobrano** [comment]
I wonder if that's a mixed environment. Ubuntu dock should be installed by default if you use gnome shell communitheme

**Comment by fthx** [comment]
I agree and am ready to get what I deserve while removing Ub Dock :-) .
But probably some users running GNOME outside Ubuntu will try this nice communitheme ?

**Comment by clobrano** [comment]
Hope so, but this way they won't have Gnome shell style, only the gtk part

**Comment by fthx** [comment]
I forgot that !
