### ISSUE TITLE
The AP settings icons in system preferences > wifi are round

### ISSUE THREAD

**Issue by fthx** [Ubuntu/gnome-shell-communitheme#66]
Hi,

Maybe a matter of taste (again) but I would feel more consistent to have access points settings icons squared with rounded corners (as in highlighting of preferences icon in system menu). I don't know if anybody share my thoughts but I run into it :-) .
(Maybe it's rather Suru-related ?)

**Comment by clobrano** [comment]
I don't understand which icons, sorry, could you post a picture?

**Comment by clobrano** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/2883614/36690812-be412b92-1b33-11e8-83f2-258aae3182a8.png)

if so, it's explicitly defined as "circular image-button" by the developer, I don't think it would be right to change its shape

![image](https://user-images.githubusercontent.com/2883614/36690848-d7ab6f66-1b33-11e8-9d2d-6f4cfb834d6b.png)

**Comment by fthx** [comment]
ok !
