### ISSUE TITLE
Looks very "Ubuntu" theme - Arrongin (GTK 3). What about default theme?

### ISSUE THREAD

**Issue by askdanielsmith** [Ubuntu/gnome-shell-communitheme#68]
![d157ea31a92c2907604d64b903ef0cfcfdab](https://user-images.githubusercontent.com/36898770/36749639-05c05bac-1c04-11e8-9b75-27d14500a5c1.jpg) 

Hey guys, what about these gtk3. Does anyone like round corners and colours in these theme? Found  it here, looks very "Ubuntu" ) 

Found it here https://www.gnome-look.org/p/1215199/

**Comment by galgalesh** [comment]
Thanks for sharing! Looks interesting but this is not the place for such open-ended discussion. There is a thread on the community forum dedicated to that: https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545

**Comment by askdanielsmith** [comment]
ok, sorry )
