### ISSUE TITLE
Ubuntu logo does not scale under 30px

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gnome-shell-communitheme#69]
At 28px it looks like below

![image](https://user-images.githubusercontent.com/2883614/36786115-7712adec-1c85-11e8-9a2a-8f612a000983.png)

**Comment by makayjozsef** [comment]
I think Ubuntu Launcher logo is too big by default and its circle background is very weird in the corner.

![screenshot-20180303105925-250x108](https://user-images.githubusercontent.com/15660274/36933051-34e479b4-1ed3-11e8-91ad-d02c19fadfb3.png)

Just make a simple orange square around the white logo (without white circle)

**Comment by clobrano** [comment]
Ubuntu logo is standardized https://design.ubuntu.com/brand/ubuntu-logo
and there is no version of it without the circle. I think the problem is that logo is 32x32px, while the dock can be smaller than this
