### ISSUE TITLE
Top-bar should have rounded corners like adwaita

### ISSUE THREAD

**Issue by NusiNusi** [Ubuntu/gnome-shell-communitheme#70]
**Please add design-label**

The top-bar should have rounded corners like the default gnome top-bar. It would fit more to the rounded-suru-style.
![bildschirmfoto von 2018-02-28 12-51-35](https://user-images.githubusercontent.com/36449926/36786344-5b6791c4-1c86-11e8-987f-f34b4f71aa1e.png)
_The curve is in reality a bit bigger._

**Comment by jim3872** [comment]
That doesn't really fit with the ubuntu dock on the left handside

**Comment by Xyaneon** [comment]
@jim3872 Not sure if it's technically possible, but what if the dock also had a rounded corner on the top-right to match?

**Comment by madsrh** [comment]
Hmm, to me it looks much cleaner without the rounded corners. @luxamman ?

**Comment by Luxamman** [comment]
Also with @madsrh - I would like to keep it straight.

**Comment by madsrh** [comment]
I'm closing this issue as the rounded corners doesn't fit with the dock on the left side and the look is more clean/simple with a straight bar.
