### ISSUE TITLE
Replace/resize ubuntu-logo-icon.svg

### ISSUE THREAD

**Issue by RBFraphael** [Ubuntu/gnome-shell-communitheme#75]
Hi!

I'm testing this theme, but the dash icon has a bug caused by image size (shows a rounded square, rather than a beautiful ubuntu logo, like original image file).
https://ibb.co/mpvSSn

My suggestion is to resize the file to fit better on dock.
https://ibb.co/gANVf7 (is on hover, so ignore the gray square in background)

Or, use a "different" icon, only with Ubuntu's logo (without white circle). Looks more likely for me haha
https://ibb.co/mEcwL7 (is on hover, so ignore the gray square in background)

Resolution: 1366x768
Dock size: 20
Dock position: Bottom

Thank you! :smile:

**Comment by clobrano** [comment]
Hi @RBFraphael, thank you for taking time to report this. It looks weird indeed, but I think we can merge this discussion with issue #73
