### ISSUE TITLE
Workspace overview improvments

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#76]
The indicator drop down menues in the gnome shell have a transparency, which looks very great (imho):
![screenshot-20180308222511-1346x861](https://user-images.githubusercontent.com/15329494/37177395-964addd8-231f-11e8-8fa7-1a5b314bde97.png)

Yet the workspace grid/area has none:
![screenshot-20180308222247-994x826](https://user-images.githubusercontent.com/15329494/37177414-a7335fee-231f-11e8-870f-20720b3a6c78.png)
Also the selected workspace has a hard square instead of a squircle selection like most elements

**Comment by clobrano** [comment]
Nice catch!

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/gnome-shell-communitheme/commit/3ff59ff8f1b9da3e1f1cd61f8557e5904f5074aa
