### ISSUE TITLE
Minor graphical issue on GTK+ window

### ISSUE THREAD

**Issue by cialu** [ubuntu/gnome-shell-communitheme#78]
Hi all,

I'm testing Ubuntu 18.04 LTS with the communitheme and using GTK+ software like Remmina, I found a minor graphical issue on the main window. It's about a round corner under the title tab, where it's not supposed to be. I don't know if this is an issue related specifically to the theme or to the application. I post a picture to explain better the issue.

![commtheme](https://user-images.githubusercontent.com/1382127/37329151-dc3aab86-269c-11e8-8919-af1131333409.jpg)

**Comment by Feichtmeier** [comment]
This is the wrong repo. Would you be so kind and reopen this in the gtk theme repo? :)

**Comment by cialu** [comment]
Yes, sorry for the inconvenience.
