### ISSUE TITLE
ubuntu-communitheme-session : Depends: gtk-communitheme but it is not going to be installed

### ISSUE THREAD

**Issue by pwd-github** [Ubuntu/gnome-shell-communitheme#79]
For some reason, this won't let me install it on 17.10. Anyone know hot fix this issue?

**Comment by didrocks** [comment]
Indeed, CommuniTheme is targetting bionic right now, and the Shell isn't backward compatible theme-wise. Please try it on bionic. 17.10 isn't supported anymore.
