### ISSUE TITLE
Seperation-line in calendar does not fade-in/out

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#80]
When the calendar in the topbar is activated the seperation-line between calendar and notifications is a bit to long visible:
![peek 2018-03-13 17-15](https://user-images.githubusercontent.com/36449926/37354843-d81e8270-26e2-11e8-9c05-e4767583353f.gif)

**Comment by Feichtmeier** [comment]
I can't reproduce this on my side. Is this still happening @NusiNusi

**Comment by NusiNusi** [comment]
Yes, still happening. Tested ambiance to make sure it is a theme-related problem:
![peek 2018-04-03 11-54](https://user-images.githubusercontent.com/36449926/38242761-e8960688-3735-11e8-9368-21ee7e002ab4.gif)
No problem here.
Should we ask in the hub if others have this problem?

**Comment by clobrano** [comment]
I can reproduce it

**Comment by Feichtmeier** [comment]
Yes, me too! But only on my host. On the VM the animation is turned off by default xD

**Comment by Feichtmeier** [comment]
Fixed after recent calendar improvements (no idea why but it's fixed)
