### ISSUE TITLE
Dont use symbolic icons in appmenu

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gnome-shell-communitheme#83]
The appmenu in the top bar uses monochrome/symbolic icons for certain apps - files, tweaks etc. As this is not for all apps, it then looks inconsistent when you start an app that does not have a matching mono icon (e.g. libreoffice), in this case the coloured icon is used.

Even when there are mono icons, they don't always align with the coloured icon. See the following for Tweaks:

![symbolic-icon](https://user-images.githubusercontent.com/1141694/37643142-8117286c-2c17-11e8-9ce4-b7425ec5d022.png)

Here the icons are completely different.

The standard Ubuntu session always uses the coloured icon - and I think the communitheme session should too.

**Comment by Feichtmeier** [comment]
@CDrummond Hmmm. I understand this argument but wouldn't it be better to provide a symbolic icon for all core apps in the suru theme?  This is a good workaround but it somehow doesn't feel right to me

**Comment by CDrummond** [comment]
@Feichtmeier but then you have some symbolic, and others not. Seems kinda odd to me. Why (as a user) should I care if an app is core or not? An app is an app.

**Comment by Feichtmeier** [comment]
Hm, because then the user knows "ok, I am using a system app now" in opposite to the third party brands. The best would be to color all icons white to match the text and the indicators.
I am not emotionally bound to these icons anyways :D Just following what everybody was proposing in the suru icon theme discussions.
@madsrh what's your opinion on this?

Also, I did a quick look in the shell theme code - I am not that sure that this could be solved in the shell theme. The best place to solve this would be the icon theme imho

**Comment by CDrummond** [comment]
How do I know I'm using a system app? What **is** a system app anyway? Geary is not a system app, but has a mono icon. Firefox has a mono icon, Thunderbird a coloured icon. I see no consistency here.

BTW, I **do** like the mono icons - just not the inconsistency.

**Comment by Feichtmeier** [comment]
I guess the appmenu tries to use the symbolic icon if provided. If not there is a fallback to the normal icon. 
When I wrote system apps I meant core apps. If some third party apps provide a symbolic icon that is a bonus :) 
As already mentioned this is rather an icon theme issue. I try some icon themes on my host and see if this is true.

**Comment by Feichtmeier** [comment]
![screenshot-20180403120803-590x161](https://user-images.githubusercontent.com/15329494/38243426-bfe7fd0c-3737-11e8-8bbb-466140f7c8e4.png)

Yup, I modified suru to inherit papirus and tadah there is the symbolic icon

**Comment by CDrummond** [comment]
Well, guess this should be closed. Suru will not (and indeed cannot) create icons for all 3rd party apps. So, I guess unless Suru removes all mono app icons, this consistency will always be there.

**Comment by CDrummond** [comment]
@Feichtmeier thanks! It doesn't personally bother me enough for an extension. But I can see it being confusing for new users. Perhaps the communitheme session could bundle this extension by default (as is done for dash-to-dock, etc)? (But I **very** much doubt that'd be approved by Canonical...)

**Comment by Feichtmeier** [comment]
@CDrummond I think the general rule is to stick to upstream as much as possible =)
I am actually considering this for notifications but the custom css properties of gnome shell are a little... inconsistent :open_mouth:
