### ISSUE TITLE
Unreadable tab headers in GNOME Terminal (light theme variant)

### ISSUE THREAD

**Issue by Sebastian-Maier** [ubuntu/gnome-shell-communitheme#85]
Minor color adjustments are necessary to make the headers in GNOME Terminal readable:
A **highlighted tab** has the same (white) text color and background color when the mouse is positioned over a tab and the **theme variant "Light"** is used.
In addition, the text colors and background colors of tabs are both gray/dark when the **window is currently in the background**.
To reproduce this problem select theme variant "Light" (Terminal -> Preferences -> Global/General -> Theme variant).

**Comment by clobrano** [comment]
Hi, thanks for taking time to report this.

My understanding is that you probably mean this [bug](https://github.com/ubuntu/gtk-communitheme/issues/227), which has just been fixed by [this](https://github.com/ubuntu/gtk-communitheme/pull/286)
