### ISSUE TITLE
Transparency does not work on the desktop and in activities.

### ISSUE THREAD

**Issue by gc-group** [ubuntu/gnome-shell-communitheme#86]
![2018-03-27 13-34-44](https://user-images.githubusercontent.com/33377623/37962549-205eb5dc-31c4-11e8-93e6-c332f80b78de.png)
![2018-03-27 13-39-42](https://user-images.githubusercontent.com/33377623/37962604-547c9a46-31c4-11e8-9136-67ba60e3e29d.png)

**Comment by Feichtmeier** [comment]
I believe @clobrano is trying out some different transparencies ATM. This could change the next days

**Comment by clobrano** [comment]
Landed with #94
