### ISSUE TITLE
gnome-system-monitor doesn't apply decoration theme

### ISSUE THREAD

**Issue by Sunderland93** [ubuntu/gnome-shell-communitheme#87]
![2018-03-29 13-15-36](https://user-images.githubusercontent.com/11344982/38082770-bdaedfa2-3358-11e8-8c0a-592bed53a460.png)

Ubuntu 18.04

**Comment by Feichtmeier** [comment]
Could you reopen this in the gtk-THEME repository? Closing this here because this is the wrong repo

**Comment by clobrano** [comment]
hey @Feichtmeier, no problem, I linked this one to a new bug here

https://github.com/ubuntu/gtk-communitheme/issues/296

**Comment by clobrano** [comment]
@Sunderland93 (or anyone else) could you check whether gnome-system-monitor is a snap package?
If so, it's a known issue that does not depend on the theme

**Comment by Feichtmeier** [comment]
The default is not a snap. I don't have this issue.

@didrocks any news on the communitheme snap? :)

**Comment by Sunderland93** [comment]
Ah, sorry. This is snap. I install gnome-system-monitor from repo and it works fine
