### ISSUE TITLE
Notification.hover misses a color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#89]
Notifications are hard to see when popped up above dark CSD header bar of gnome3 CSD apps like for example nautilus/files and then hovered:

![screenshot from 2018-03-31 02-26-47](https://user-images.githubusercontent.com/15329494/38157904-d9d55164-348b-11e8-983c-8b9f5ade7635.png)

A short test with the following is easier to see:
// Banners
  .notification-banner {
    font-size: 11pt;
    width: 34em;
    margin: 5px;
    border-radius: $medium_radius;
    color: $osd_fg_color;
    background-color: $osd_bg_color;
    border: 1px solid $osd_borders_color;
    //box-shadow: 0 1px 4px black;
    box-shadow: none;
    &:hover, &:focus { background-color: opacify(mix($osd_bg_color, $base_hover_color), 1); border: 1px solid $dark_fill;} <-------

![screenshot from 2018-03-31 02-30-17](https://user-images.githubusercontent.com/15329494/38157910-f957e43e-348b-11e8-8245-05ddc67b2f08.png)

@clobrano @madsrh what do you think? :O

**Comment by madsrh** [comment]
@Feichtmeier This is better, but still not perfect. I been thinking about this too 😃 How about using a light/gray/transparent background? Basically just anything that isn't dark, since it blends too much into the headerbar 🤔 

They are styled the same way as the notification when I delete files etc., right? Or am I mixing the two together here? 

From the screenshots below I like the default Adwaita the most. Here's some inspiration from a few other themes:
![screenshot](https://user-images.githubusercontent.com/3986894/38161675-047ac8d4-34d4-11e8-934a-2aaabf3ed308.gif)

**Comment by Feichtmeier** [comment]
The "blending too much in the headerbar" is also a problem with the popover menues :( 
![screenshot from 2018-03-31 15-03-42](https://user-images.githubusercontent.com/15329494/38163459-bb672aa4-34f4-11e8-9eae-53e91b1832b9.png)

**Comment by madsrh** [comment]
Yes. These are two different things (GTK theme and shell)?

I'll try to mockup a suggestion tonight.

**Comment by Feichtmeier** [comment]
No that is the same thing. Popover/popup menus from shell and notifications from shell :)

**Comment by Feichtmeier** [comment]
@madsrh what about porcelain message with a silk border and a light shadow?

Normal notification:

![screenshot from 2018-03-31 18-00-31](https://user-images.githubusercontent.com/15329494/38165107-bde94838-350e-11e8-8bb0-874e5f66e07e.png)

Hovered notification:
![screenshot from 2018-03-31 18-07-19](https://user-images.githubusercontent.com/15329494/38165113-c45983ae-350e-11e8-9abd-b2b3fff4f7a3.png)

Chaning "color" does not change the text color though. Gets overwritten elsewhere which I can't find atm, but yes the text would need to be dark then :)

 .notification-banner {
    font-size: 11pt;
    width: 34em;
    margin: 5px;
    color: black;
    border-radius: $medium_radius;
    background-color:$porcelain;
    border: 1px solid $silk;
    box-shadow: 0 2px 5px transparentize(black, 0.75);
    &:hover, &:focus { background-color: opacify(mix($silk, $base_hover_color), 1); }

**Comment by madsrh** [comment]
I really like the porcelain look, if it fits with the rest of the UI 👍 I could even imagine a pure white background to make the notification really pop - I think the shadow is essential here. These could also work inside the notebook, like when deleting a file.

I tried #888 and #666, but it doesn't work. The other option I could see would be dark #111 with a bit of transparency.

[_Click fullscreen..._](https://user-images.githubusercontent.com/3986894/38166588-82924e0c-3526-11e8-8de3-67aed80884c1.gif)
![no](https://user-images.githubusercontent.com/3986894/38166588-82924e0c-3526-11e8-8de3-67aed80884c1.gif)

**Comment by Feichtmeier** [comment]
White looks pretty cool!

I fail to find 
a) the text-color property that overwrites all text colors
b) the portion of code who is responsible for the actions area

![screenshot from 2018-03-31 21-35-13](https://user-images.githubusercontent.com/15329494/38166897-f71330a2-352b-11e8-81ca-6e8125e8f40f.png)
![screenshot from 2018-03-31 21-39-39](https://user-images.githubusercontent.com/15329494/38166899-0ae84f54-352c-11e8-9c2f-dee5d37d8ba4.png)

**Comment by nana-4** [comment]
@Feichtmeier You can change the text colors like this:

```scss
  // Banners
  .notification-banner {
    font-size: 11pt;
    width: 34em;
    margin: 5px;
    border-radius: $medium_radius;
    color: $inkstone;
    background-color: $porcelain;
    border: 1px solid $silk;
    box-shadow: 0 2px 5px transparentize(black, 0.75);
    &:hover, &:focus { background-color: opacify(mix($silk, $base_hover_color), 1); }

    &, &:active { .message-title { color: $inkstone; } }
    &, &:active { .message-content { color: $slate; } }
``` 

Though I'm not sure if the light notification really fits the rest of the shell's design. ;)

**Comment by Feichtmeier** [comment]
Yeah that nesting did the trick! Here we go:
Imho this fits pretty well - ofc a little bit color consistency would 
![screenshot from 2018-04-01 02-02-12](https://user-images.githubusercontent.com/15329494/38170604-61db524e-358a-11e8-8841-fc7bf4fdb7f5.png)
![Uploading Screenshot from 2018-04-01 02-02-16.png…]()
![Uploading Screenshot from 2018-04-01 02-02-51.png…]()

**Comment by nana-4** [comment]
Indeed light one looks much better and makes sense.

**+1** for white notifications! :+1:

**Comment by Feichtmeier** [comment]
I'd make a PR if @clobrano  and @madsrh  agree, too :dancer:

**Comment by madsrh** [comment]
@Feichtmeier Yes +1

Does this apply to the notifications I mentioned earlier in Nautilus? They should IMO be styled similarly

**Comment by Feichtmeier** [comment]
@madsrh 
No these are in-app specific notifications for nautilus (I believe - would need to confirm this, but I am quiet sure)

**Comment by madsrh** [comment]
@Feichtmeier Yes they are easy to see, but the button blends too much into the background IMO. We could fix that, or (my initial thought) style these like the white notifications you just suggested above. As you see above, white notifications in Nautilus are also used in United, Pop OS and other themes.

Options: 
A) tweak the current dark style
B) style these white like your suggestion

@c-lobrano what's your opinion on this?

**Comment by Feichtmeier** [comment]
@madsrh How about cutting of the transparency and use $headerbar_bg_color ? :)

![screenshot from 2018-04-01 16-09-02](https://user-images.githubusercontent.com/15329494/38174047-595235ec-35c7-11e8-82f5-35d948d87221.png)

**Comment by madsrh** [comment]
@Feichtmeier A lower transparency would be better because then the contrast between the background and the button would be bigger. Like Adwaita [here](https://user-images.githubusercontent.com/3986894/38161675-047ac8d4-34d4-11e8-934a-2aaabf3ed308.gif)

**Comment by Feichtmeier** [comment]
I'll open another issue for this in the GTK repo, since the nautilus notifications are the GTK app notifications, it is not the gnome shell =)
PR for the white shell notifications is being reviewed by @clobrano :)

**Comment by Feichtmeier** [comment]
fixed with https://github.com/ubuntu/gnome-shell-communitheme/pull/90
