### ISSUE TITLE
Installing Communi theme on fedora 27

### ISSUE THREAD

**Issue by PadamSethia** [ubuntu/gnome-shell-communitheme#91]
I really love this theme and would like to install it on Fedora Workstation 27 , I would be really glad if someone could help me with this.
Thank you!

**Comment by Feichtmeier** [comment]
Gnome Shell theme

# Download the repository from github
git clone https://github.com/ubuntu/gnome-shell-communitheme.git
cd gnome-shell-communitheme
# Initialize build system (only required once per repo)
meson build --prefix=/usr
cd build
# Build and install
sudo ninja install
If you want to change the GDM look and point to the same stylesheet. You only need to do this once.

update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css /usr/share/gnome-shell/theme/communitheme/gnome-shell.css 15
GTK theme

# Download the repository from github
git clone https://github.com/ubuntu/gtk-communitheme.git
# Enter the directory you just cloned
cd gtk-communitheme
# Initialize build system (only required once per repo)
meson build --prefix=/usr
cd build
# Build and install
sudo ninja install
Suru Icon theme

# Download the repository from github
git clone https://github.com/ubuntu/suru-icon-theme.git
# Enter the directory you just cloned
cd suru-icon-theme
# Initialize build system (only required once per repo)
meson build --prefix=/usr
cd build
# Build and install
sudo ninja install
Now everything should be in place. Reboot and login to the Communitheme on Xorg session and set the Communitheme themes using Gnome Tweaks.

**Comment by PadamSethia** [comment]
@Feichtmeier Hey , sudo ninja build doesn't seem to work , shows build.ninja no such file pr directory

**Comment by Feichtmeier** [comment]
Install meson

**Comment by PadamSethia** [comment]
@Feichtmeier already installed

**Comment by PadamSethia** [comment]
yes

**Comment by Feichtmeier** [comment]
You got telegram ? So we don't need to spam GitHub

**Comment by PadamSethia** [comment]
riot.im ?

**Comment by PadamSethia** [comment]
@Feichtmeier I'm getting meson build error , meson.build:6:0: ERROR: Program(s) ['sassc'] not found or not executable . Any idea ?

**Comment by Feichtmeier** [comment]
Install sassc

**Comment by PadamSethia** [comment]
Yep , already tried that `sudo yum install scssc` package not found error

**Comment by clobrano** [comment]
> Install sassc

not scssc

**Comment by PadamSethia** [comment]
Shhaaa , made a typo thanks installed sassc . After i run meson build command , there is a build file within which there are two more files meson-private and meson-logs.

**Comment by PadamSethia** [comment]
@Feichtmeier @clobrano Ok so i seem to have successfully installed all the packages , i have the look on the app windows but when i login by setting community theme on xorg , i am dropped back to the login screen , can't seem to start the desktop when ubuntu communitheme on xorg is selected.
P.S : It's for both the communitheme login options.

**Comment by nana-4** [comment]
@PadamSethia Maybe "Communitheme session" doesn't work on distros other than Ubuntu.

Try to run:

```
sudo ln -sT /usr/share/gnome-shell/theme/communitheme /usr/share/themes/Communitheme/gnome-shell
```

Then launch gnome-tweak-tool. You should be able to select Communitheme from "Shell".

**Comment by PadamSethia** [comment]
@nana-4 Yep that seemed to work. Thanks a lot.
