### ISSUE TITLE
Change the overview window selection border color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#92]
Concerning the discussion found at the bottom of  https://github.com/ubuntu/gtk-communitheme/issues/289

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/gnome-shell-communitheme/pull/90

**Comment by Feichtmeier** [comment]
All those "elegance"-enhancement initiated by @nusinusi make me feel that the border in the window overview is a bit too big now

![screenshot from 2018-04-24 23-12-41](https://user-images.githubusercontent.com/15329494/39214578-3a8d567c-4815-11e8-890b-1eca79fc0b71.png)

What do you guys think?
@madsrh @luxamman @clobrano @godlyranchdressing @nusinusi

**Comment by clobrano** [comment]
Agree with @madsrh. In the screenshoot above it not even so immediate to see the highlighted window
