### ISSUE TITLE
Enhancing the readability of shell popups above dark headers

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gnome-shell-communitheme#96]
I believe we got a contrast issue here between the dark popup menus all over the shell above dark elements for example the header bars:

![38327665-14a5f1a2-3849-11e8-8bfa-115a3ac7588b](https://user-images.githubusercontent.com/15329494/38391717-4c2ba0a4-3925-11e8-9683-db3541aaa697.png)

Now, there were several ideas

A) Leave it as it is

B) changing the dark background back to a lighter dark:
![38327701-247243c4-3849-11e8-8501-f6aa0b3ca65b](https://user-images.githubusercontent.com/15329494/38391881-ef061e8a-3925-11e8-86d7-c853776382ed.png)

C) switching the shell popovers to light like for example elementary os uses them
![1_0lqz38e0mjc5vfpam04pua 2x](https://user-images.githubusercontent.com/15329494/38391891-f4cb5772-3925-11e8-9e62-3a1e9e4fd283.png)
Or like the ones we use in the gtk theme (which should be the one to use for the shell imho IF we would decide to use the white):
![screenshot-20180405231911-296x643](https://user-images.githubusercontent.com/15329494/38392444-d10af764-3927-11e8-915d-9dcabc4b75b2.png)
Unity8 has white popups too as found in this screenshot:
![ce65e0c756c33ce18aa867838c0f94359ea5011e_1_690x431](https://user-images.githubusercontent.com/15329494/38807128-dca63546-417b-11e8-8bcb-4f627ce786e6.jpg)

D) I came up with a fourth option, to change the border to a transparent 2 px border:
![transparent2px](https://user-images.githubusercontent.com/15329494/38391775-841b81dc-3925-11e8-94f3-b32dce11600b.png)
Which reminds me a lot of how unity7 did it :) though compiz had blur *cry*

Since I will probably need several days for the light version, I wanted to share this first and let you guys (@madsrh @clobrano @godlyranchdressing @nana-4 ) think over this for a day and share your opinion on this :)

**Comment by madsrh** [comment]
Nicely summed up @Feichtmeier 😃 I'll tag @luxamman here as well, since he's back online :satellite:

**Comment by Luxamman** [comment]
Yes thanks @Feichtmeier - I also see that this can be improved a little. I guess that the contrast on certain displays is hard to get - we will have a look at the borders and border colors.

**Comment by Feichtmeier** [comment]
@Luxamman what's your general opinion on a "white" shell? Excluding the top menu. 
Unity8 had/has no shell. They use notifications for both the regualar notifications and the OSD popups. And those are white. Our notifications are white now, too.
Unity8 also had/has nothing like the calendar popup.  
I still owe you some mockups but I am short on freetime atm

**Comment by NusiNusi** [comment]
@Luxamman @Feichtmeier 
here are some examples from the canta-theme:
![bildschirmfoto von 2018-04-10 13-10-09](https://user-images.githubusercontent.com/36449926/38553782-a5fa5802-3cc0-11e8-9c1a-221c68646f30.png)
![bildschirmfoto von 2018-04-10 13-10-23](https://user-images.githubusercontent.com/36449926/38553792-ab6a9522-3cc0-11e8-8a3b-4ed5b5c9a825.png)

Note the pic with the maximized window. The shadow helps a lot with the contrast issue. This would only work with white (bright) menus. The shadow of dark menus over dark menubar wouldnt be easy recognizable which would lead to the same problem the theme already has: popup-menus melt with the dark headerbar. In the evening i could look other themes up if you want  more examples before making a decision.

**Comment by Luxamman** [comment]
@Feichtmeier 
Overall for me: it depends a lot on the whole system and look. Since we go a darker design way than other systems, but brighter than Gnome and others (in some ways) for now it works out nice for me. 

We are not there yet, but the point for me is just, that we have kind of three layers of interaction: 
The Shell/System, the control layer (mostly the headerbar) and the app/program content. 

So the separation between the system (dark), the control layer (dark) and the content (mostly much brighter, or white) is visually defined.  

Like said I want to still try some adjustment and see if this works out better. For me, it is also important not to mix too many styles an too harsh contrast to have a harmonizing overall look. Let's see^^

Greetings and thx for asking!

**Comment by Feichtmeier** [comment]
Hello again everyone

This is how a porcelain shell would look like:

![whiteshellplease](https://user-images.githubusercontent.com/15329494/38780634-23356bfa-40da-11e8-9587-9a4369ae7b10.png)

I really like it and I can read everything even when I sit with my laptop outside. 
I have a really good screen but the current dark shell is (even if it looks freaking nice) really hard to read in none perfect environments =)

**Comment by NusiNusi** [comment]
PERFECTION!

**Comment by Feichtmeier** [comment]
@NusiNusi Not realy! xD Just changed two colors =D (took  me some time to realize though)
Let's wait for @madsrh + @Luxamman

**Comment by NusiNusi** [comment]
@Feichtmeier Have you seen my picture of the canta-theme? It uses a shadow instead of a dark border. What do you think?

**Comment by Feichtmeier** [comment]
I like the dark border because it gives me a "gnome-shell feeling". Whatever that is. :)
The shadow is also used in our gtk popover shown in the first post. It's great. 
Yet my personal fav goes with the dark border for the theme.

**Comment by Feichtmeier** [comment]
If the dark border is not the way to go I would rather prefer the GtkPopovers. But it's strange to realize in the shell theme. There is that arrow class which I didn't understand yet. Maybe @nana-4 could make some code for shell popovers that look like the ones from the Gtktheme? I can't place a shadow in the popover. No idea why

.popup-menu-boxpointer,
  .candidate-popup-boxpointer {
    -arrow-border-radius: $medium_radius;
    -arrow-background-color: $_dialog_bg_color;
    -arrow-border-width: 1px;
    -arrow-border-color: $osd_borders_color;
    -arrow-base: 24px;
    -arrow-rise: 11px;
    -arrow-box-shadow: 0 1px 3px black; 
  }

**Comment by NusiNusi** [comment]
+1 for getting rid of the arrow. Maybe we could open for this a new ticket in the future.

**Comment by Feichtmeier** [comment]
Hm... I would rather keep the arrow and so then live without a shadow. The gtk theme got arrows too in the popover menues and they fit well imho

**Comment by godlyranchdressing** [comment]
@NusiNusi I don't care for the arrow, but I do get its purpose. I think opening another issue would be the way to go but I can see it most likely being kept for usability reasons.

**Comment by NusiNusi** [comment]
@godlyranchdressing I think the same. The designers decide this @madsrh @Luxamman . We can look at this later.

**Comment by Feichtmeier** [comment]
Here is a slightly different version. Lighter background but also softer borders:

![screenshot from 2018-04-18 17-18-28](https://user-images.githubusercontent.com/15329494/38941755-8792bc10-432d-11e8-8e1f-0d56b4783b40.png)
![whiteshell01](https://user-images.githubusercontent.com/15329494/38941757-87c5df6e-432d-11e8-8fba-543a59775595.png)
![whiteshell02](https://user-images.githubusercontent.com/15329494/38941758-87eee6f2-432d-11e8-8555-045f38e945b4.png)
![screenshot from 2018-04-18 17-24-26](https://user-images.githubusercontent.com/15329494/38941759-8816c03c-432d-11e8-9488-1436084d1c71.png)

**Comment by godlyranchdressing** [comment]
@Feichtmeier how about a mixed style?
![a](https://user-images.githubusercontent.com/27529229/38947157-b319094e-4309-11e8-803d-426e1180265c.jpg)
![b](https://user-images.githubusercontent.com/27529229/38947158-b332e102-4309-11e8-8dcb-f63736be7aef.jpg)
![c](https://user-images.githubusercontent.com/27529229/38947159-b34a4d06-4309-11e8-926e-0dda162f5afb.jpg)

**Comment by NusiNusi** [comment]
@godlyranchdressing That could be a good solution but it would have to be the other way around. So popover-menus of gnome-shell has to be bright/white and the other parts could stay dark. Or else the contrast issue (the reason why @Feichtmeier opened this issue) would still be present.

**Comment by Luxamman** [comment]
Since we have generally made things much brighter and thus a clearer line (clean, modern, with a good readability), I think a lot about making the shell popups brighter too. 

With that we would leave on of the last vanilla Gnome looks aside (or have a dark version of the theme sometime), but maybe the readability (white popup on a white background like LibreOffice) is equally bad in some circumstances. 

Definitely something to get used to. But the look is then unified and the contrast difference for the eyes is not so rough anymore. In addition, the dark in the design would continue to establish itself as a background.

**Comment by Feichtmeier** [comment]
@Luxamman I love the dark shell - we could also lighten the header bars by 5% in the gtk-theme

**Comment by godlyranchdressing** [comment]
@Feichtmeier changing `$variant: 'dark';` to `$variant: 'light';` in gnome-shell.scss should have the theme compile using the light colors, so we won't have to do another branch. We can both compile the light version and tidy up things, since there's usually just a couple readability issues to fix. I think it'll be better to leave that until after the "main", dark theme is done.

**Comment by Feichtmeier** [comment]
@godlyranchdressing that would be the best solution ofc. But I think some colors are missing and some if/else checks, too.

**Comment by Feichtmeier** [comment]
Ok, there are ofc more solutions to the problem. I've "found" one very subtle change which is quiet effective.
Changing the osd border color to
$osd_borders_color: transparentize(white, 0.8);

- we would still have the cool dark shell
- the contrast problem gets almost nullified 

![whieborder02](https://user-images.githubusercontent.com/15329494/39122930-9c1a54e6-46f6-11e8-8834-d165ad2f465e.png)
![whiteborder01](https://user-images.githubusercontent.com/15329494/39122932-9c360128-46f6-11e8-96c9-a4f282e9917d.png)

This would not affect the great idea to generally offer a white and dark shell

**Comment by Feichtmeier** [comment]
@Luxamman @madsrh @NusiNusi @clobrano 
Please test the brighter, transparent border:
https://github.com/ubuntu/gnome-shell-communitheme/tree/lighten_up_osd_border

**Comment by Feichtmeier** [comment]
Adjusted the calendar line:
![screenshot from 2018-04-23 15-28-46](https://user-images.githubusercontent.com/15329494/39129556-16f46512-470b-11e8-9ef0-8efdb51c67d4.png)

**Comment by Feichtmeier** [comment]
@Luxamman @madsrh 
for me this issue is fixed. Its in master: what do you say? Try it at day, at night, and in dark and bright environments please. My impression is that this fixes the issue and still looks sharp and with style.

**Comment by Luxamman** [comment]
Fine with me!

**Comment by madsrh** [comment]
😁
