### ISSUE TITLE
Make border of password-entryfield orange

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gnome-shell-communitheme#99]
This is how it looks at the moment:
![bildschirmfoto von 2018-03-29 18-08-05](https://user-images.githubusercontent.com/36449926/38454701-4d15eba8-3a6c-11e8-9d28-7abe6d039050.png)

This is how it should look:
![bildschirmfoto von 2018-03-29 18-08-05a](https://user-images.githubusercontent.com/36449926/38454706-60824236-3a6c-11e8-803f-b201d9074582.png)

This was already discussed somewhere else. But i could not find a ticket directly mention this.

EDIT: it should only be orange when the entry-field is **selected**. This way the user knows that he can start enter his password. But not sure if this field can be unselected...

**Comment by Feichtmeier** [comment]
Great idea +1 from me lets see what the others say

**Comment by clobrano** [comment]
Thanks @NusiNusi , this is exaclty what we have in our backlog. The basic widgets should look the same as gtk-communitheme, unless particular exceptions
